### ISSUE TITLE
Cannot get video component to work

### ISSUE THREAD

**Issue by tonyneel923** [shoutem/ui#107]
I tried all the example videos but could not get it to work. Has anyone had success with this component?

**Comment by SoHotSoup** [comment]
This is how we are using it.

```javascript
<Video source={{ uri: "https://www.youtube.com/watch?v=1tavDv5hXpo" }} />
```

Could you share with me what did you try?

**Comment by tonyneel923** [comment]
I copied that exact line and nothing shows up. I will attempt to further debug to give you more information.

**Comment by tonyneel923** [comment]
It appears my video enters into if (sourceReader.isEmbeddableVideo()) but never hits function Video.

**Comment by tonyneel923** [comment]
`import React, { Component } from 'react';
import { AppRegistry, StyleSheet, View, ListView } from 'react-native';
import Comment from './app/components/Comment.js';
import { StyleProvider } from '@shoutem/theme';
import AppTheme from './app/theme/AppTheme.js'
import { Video } from '@shoutem/ui';


export default class Comments extends Component {
  render() {
    return (
       <Video source={{ uri: "https://www.youtube.com/watch?v=1tavDv5hXpo" }} />
    );
  }
}


AppRegistry.registerComponent('Comments', () => Comments);`

I got my index.ios all the way down to this and can still not play video. Any suggestions?

**Comment by SoHotSoup** [comment]
Hm, @tonyneel923, I have tried to compare this with our code, and I can't see any difference. Do you even see thumbnail?

**Comment by tonyneel923** [comment]
Thanks @ikalafat that did it!
