### ISSUE TITLE
Invalid selectedOption

### ISSUE THREAD

**Issue by acomito** [shoutem/ui#114]
What does selected option take? I can't seem to pass it what it needs:

![image](https://cloud.githubusercontent.com/assets/12701635/21447268/4fdae968-c8a0-11e6-9581-1ea485e77670.png)

```
const MyNav = () => (
	<NavigationBar
		rightComponent={<DropDownMenu
							options={[
							{ name: 'All', value: 1 },
							{ name: 'Sport', value: 2 },
							{ name: 'World', value: 3 },
							{ name: 'Lifestyle', value: 4 },
							{ name: 'Food', value: 5 }]}
							titleProperty="name"
							valueProperty="value"
							onOptionSelected={()=>console.log}
							/>}
	/>
);
```

**Comment by SoHotSoup** [comment]
This is actually change we introduced in our last release.
Take a look at this example:
https://github.com/shoutem/ui/blob/develop/examples/components/DropDownMenu.js

`selectedOption` should be a member of `options` array, so passing `options` explicitly is not the good way to go.
