### ISSUE TITLE
NavigationBar: getScene is not a function

### ISSUE THREAD

**Issue by phantomk** [shoutem/ui#117]
when i use NavigationBar just like `<NavigationBar />`  
![image](https://cloud.githubusercontent.com/assets/3520021/21533502/1d8d84ca-cd96-11e6-9e07-74c8604ab891.png)

**Comment by SoHotSoup** [comment]
Hey @phantomk, it seems you are using `NavigationBar` from `@shoutem/ui/navigation` which expects to be used as a child component of `CardStack` from our toolkit. If you want to use our component `NavigationBar` and you are already using some navigation component just import `NavigationBar` from `@shoutem/ui`. I know it's confusing, but we didn't want to break any existing apps that are already using `NavigationBar` when we introduced one that works with our `CardStack`

**Comment by phantomk** [comment]
ok, thinks @SoHotSoup
