### ISSUE TITLE
font rendering issues in android

### ISSUE THREAD

**Issue by acornejo** [shoutem/ui#118]
Tested on exponent app on android on nexus 6p phone. The font used by the UI toolkit in android looks terrible, this is especially visible with smaller sized fonts.

In the word Choosing look at the thickness of the 'o' compared to the 'h' or other letters. This is visible in the screenshot but much more noticable on the physical phone (since resolution is so high and screen is small compared to the laptop screen where I view this screenshot).

![screenshot_20161230-074617](https://cloud.githubusercontent.com/assets/83786/21567869/881323b2-ce64-11e6-9be5-faffed42d924.png)

**Comment by acornejo** [comment]
Turns out this was an issue with the version of the app made available in exponent by the community. Will open another issue so that the ahoutem website includes link to official exponent URL (so folks can test in phone to get a feel for the UI).

**Comment by Unforgiven-wanda** [comment]
I'm having the same issue on Android as well, except the fonts look much, much worse.
Has there been any progress on this?

**Comment by acornejo** [comment]
If you tried it within exponent, make sure to use this URL:

exp://exp.host/@community/shoutem-ui-examples

**Comment by Unforgiven-wanda** [comment]
A month and several updates later, it seems this issue is ever present.
I didn't try it with Exponent, but in a simple RN project, the font rendering is horrendous and I have no idea why. This is also true for the Restaurent example app in this project.
Are there other people still encountering this issue?

**Comment by ng-hai** [comment]
Same issue

**Comment by mypark** [comment]
I think this issue needs to be re-opened
