### ISSUE TITLE
fullwidth input is tiny

### ISSUE THREAD

**Issue by acornejo** [shoutem/ui#119]
tested on android exponent app, on nexus 6p.

Image is a thousand words:

![screenshot_20161230-075345](https://cloud.githubusercontent.com/assets/83786/21567973/64eee2ee-ce65-11e6-9a9e-045e9fd838b6.png)

**Comment by acornejo** [comment]
Turns out this was an issue with the version of the app made available in exponent by the community. Will open another issue so that the ahoutem website includes link to official exponent URL (so folks can test in phone to get a feel for the UI).

**Comment by ng-hai** [comment]
I have same issue like you.
How do you fix it ?
