### ISSUE TITLE
Official exponent url

### ISSUE THREAD

**Issue by acornejo** [shoutem/ui#120]
Documentation should include a link to the example apps in exponent.

This will allow folks to test ahoutem UI kit in their phones to judge usability without having to build anything.

There are a couple of links that appear on Google searches but they seem to be non official and possibly outdated (I got font issues in one of them, and missing components in the other).

**Comment by SoHotSoup** [comment]
Hi @acornejo thank you for pointing that out.
@brentvatne could you please help me with this? I know that you had to do some customizations to get it work in The Exponent, but is there anything yet to be done after we have released v0.10.2? I can make official example apps... :)

**Comment by brentvatne** [comment]
seems useful!

@SoHotSoup - it should just work out of the box now, once you have loaded the fonts -- eg: https://github.com/exponent/shoutem-example

(See the font loading code here: https://github.com/exponent/shoutem-example/blob/master/main.js#L16-L41)

**Comment by SoHotSoup** [comment]
Great! Thank you!
