### ISSUE TITLE
React-native v0.40.0 support

### ISSUE THREAD

**Issue by cyakimov** [shoutem/ui#124]
RN 0.40 introduced a [breaking](https://github.com/facebook/react-native/releases/tag/v0.40.0) change that makes this library incompatible with it.

**Comment by karlozadro** [comment]
Ran into this issue this morning. To fix a fresh install, all you have to do is manually update every `.h` and `.m` file within `RNVectorIcons.xcodeproj` and `RNShare.xcodeproj` that imports a React header (`.h`) file.

So change every instance of lines like `#import "RCTConvert.h"` to `#import <React/RCTConvert.h>` and so on for every `#import "RCTxxxxxxx.h"`.

**Comment by g3r4n** [comment]
react-native-vector-icons PR : https://github.com/oblador/react-native-vector-icons/pull/376
react-native-share PR : https://github.com/EstebanFuentealba/react-native-share/pull/95
Shouldn't be too long

**Comment by juanmiret** [comment]
Hey! @karlozadro Thank you, I'm running into this issue right now, but, where are those files? Seems I can't find them :/

**Comment by karlozadro** [comment]
@juanmiret Glad you found them! For anybody else that needs a visual, it's these files right here.
![where-to-find-the-files](https://cloud.githubusercontent.com/assets/4347329/21809891/9bda63f4-d717-11e6-8cbf-8f58c7a1977f.jpg)

**Comment by JulianKingman** [comment]
`react-native-linear-gradient` also needs to be updated to v2
