### ISSUE TITLE
missing input components

### ISSUE THREAD

**Issue by acornejo** [shoutem/ui#126]
Some crucial input components are missing from this toolkit.

Namely, a checkbox and radio group component would be great.

**Comment by SoHotSoup** [comment]
Hey @acornejo, we are aware of that issue and our designers already work on it. We have checkbox already finished and we use it for our internal projects, I will see what yet have to be done to make it available publicly.

Thank you for being such active on our repo, and feel free to contribute with any component. :)

**Comment by acornejo** [comment]
Thank you guys for such an amazing project.

If you share a mock-up/screenshot of the check box/radiobox I'll be happy to contribute an implementation (already did versions of both of these for my own project, but I am sure whatever your designers came up with will be prettier)

**Comment by SoHotSoup** [comment]
Hey @acornejo I forgot to message you about it, but we introduced `Switch` component in the meantime, also, we have `NumberInput` and `SearchBar` ready and we are testing them internally, but most important thing, we have added some new icon names that you could use to make `RadioButtonGroup` and `Checkbox`. Tell me if you are still interested in that contribution, so I will write you my ideas about API.
