### ISSUE TITLE
Error while runing example app

### ISSUE THREAD

**Issue by kholiavko-roman** [shoutem/ui#131]
I try to run sample app on android device and receive error
**"undefined is not an object (evaluating 'jobModule.jobs)"**
![screenshot_20170115-004506](https://cloud.githubusercontent.com/assets/16399378/21958660/39a6062c-dabc-11e6-898a-a30374d38b2e.png)

**Comment by Slumber86** [comment]
Same here for iOS: 

![simulator screen shot 17 gen 2017 17 06 37](https://cloud.githubusercontent.com/assets/7034226/22028375/48abd562-dcd7-11e6-852d-36fe41ebe952.png)

**Comment by SoHotSoup** [comment]
Hey @kholiavko-roman could you please give us more details on it?
