### ISSUE TITLE
Ask for supporting grid layout component

### ISSUE THREAD

**Issue by paduvi** [shoutem/ui#141]
Can you add component supporting for grid layout? Something like [react-native-easy-grid](https://github.com/GeekyAnts/react-native-easy-grid), and combine with some styles, props of your own theme ui.

```
<Grid>
    <Col>1</Col>
    <Col>
        <Row>2</Row>
        <Row>3</Row>
    </Col>
</Grid>
```

It will be really convenient to have all-in-one package, which won't need to install 2 packages: 1 for grid layout, 1 for ui component anymore.

Thanks

**Comment by ikalafat** [comment]
Hi @paduvi 

Have you seen this component which allows you to create grid layout?
http://shoutem.github.io/docs/ui-toolkit/components/grid-view

**Comment by paduvi** [comment]
Hi @ikalafat
I have seen it before. But It's suitable for render data list as columns of cells, not for this circumstance. I just look for something like Bootstrap css grid system in web

**Comment by SoHotSoup** [comment]
@paduvi This could be achieved with flexbox in other hands you can do something like this:
```javascript
<View styleName="horizontal">
  <View styleName="vertical">
    <Row></Row>
  </View>
  <View styleName="vertical">
     <Row></Row>
  </View>
</View>
```
