### ISSUE TITLE
Release failed because of react-native-share 1.0.18

### ISSUE THREAD

**Issue by g3r4n** [shoutem/ui#142]
XCode Release failedb because of new header introduce with RN 0.40.0
React native : 0.39.2

**Comment by rsekulic1** [comment]
@g3r4n Thank you for submitting the issue and sorry for a late response. We're currently working on fixing the majority of the issues and we will release a new version of `@shoutem/ui` hopefully next week with the fix included.

**Comment by SoHotSoup** [comment]
Fixed with latest release.
