### ISSUE TITLE
How do I style a TextInput with a button on the side in the same row?

### ISSUE THREAD

**Issue by mypark** [shoutem/ui#144]
I'm trying to basically create a search input field with a cancel button next to it but the TextInput doesn't show and the formatting is broken.  How do I get the input box to show up correctly?  I can't see the input box and the button margins seem off.

![screen shot 2017-01-25 at 8 50 26 am](https://cloud.githubusercontent.com/assets/470164/22292877/6b6219c2-e2db-11e6-87ba-0492c8bfd196.png)

 Should I use a Row instead of a View?  However using a row doesn't seem to work well either. 

Do you have an example of a form with buttons next to inputs using shoutem UI?

```
          <View styleName="horizontal space-between wrap">
            <TextInput
              placeholder="Search"
              autoFocus={ true }
              returnKeyType="search"
              clearButtonMode="while-editing"
            />
            <Button styleName="right-icon" onPress={() => {
                this.setModalVisible(!this.state.modalVisible)
              }}>
              <Text>Cancel</Text>
            </Button>
          </View>
```

**Comment by Air-Miha** [comment]
@mypark,

I answered this question on StackOverflow recently, but I don't know if you've seen it:

http://stackoverflow.com/questions/41853647/how-do-i-style-a-textinput-with-a-button-in-a-row-using-shoutem-ui-for-react-nat

Let me know if you need any more details!

**Comment by Air-Miha** [comment]
I'm closing this issue for now since it's been answered on SO.
