### ISSUE TITLE
Video API

### ISSUE THREAD

**Issue by dkaushik94** [shoutem/ui#146]
I have had a problem using the documentation efficiently as it just describes the components properly but isn't very exhaustive but please correct me if I am wrong. I am using the Video module now and can't find options for fullscreen viewing and thumbnails for custom videos which aren't YouTue or Vimeo. Is there an option or prop I need to pass or do I need to code for these functionalities? I really like the UI toolkit and hence I am using it regardless. But I am not really sure about its maturity or I am really naive, either of the two cases. :(

**Comment by zrumenjak** [comment]
The `Video` component currently supports YouTube and Vimeo videos out of the box. All other videos will be rendered in a WebView using a `video` HTML element. This may be good enough for you, depending on the video source that you are using. You can find more details here: https://github.com/shoutem/ui/blob/develop/components/Video/Video.js#L31-L50.

It may be useful to introduce a prop that would allow developers to specify if a video URL should be embedded or not. We have no plans to support this at the moment, but you can submit a PR if this is something that would be useful to you.
