### ISSUE TITLE
Unrecognized font family 'Rubik-Regular'

### ISSUE THREAD

**Issue by oliwerhelsen** [shoutem/ui#149]
Reffering to issue #95 . Still not working.

**Comment by hwkongsgaard** [comment]
Same here

**Comment by hwkongsgaard** [comment]
Also the same problem with react native 0.41

**Comment by roslaneshellanoo** [comment]
Same here

**Comment by rsekulic1** [comment]
@oliwerhelsen @hwkongsgaard @roslaneshellanoo We're currently working on a fix for this issue. We will release a new version of @shoutem/ui hopefully next week with the fix included.

**Comment by oliwerhelsen** [comment]
Thanks @rsekulic1 !

**Comment by rozenshtein** [comment]
@rsekulic1 it's enough to update packages.js with newer versions of linear gradient library and vector icons one

**Comment by alland67** [comment]
Same problem here.

**Comment by bluetidepro** [comment]
Having the same issue, hopefully a fix can come quickly! :)

**Comment by Connorelsea** [comment]
Not working for me here. Cannot use this library

**Comment by pferdefleisch** [comment]
Thanks to @rozenshtein, I got this to work by running this in the project's root:

```bash
npm i -S react-native-vector-icons
npm i -S react-native-linear-gradient
# I don't know if this is necessary but I ran it anyway
react-native link

react-native run-ios
```

And it loaded with no errors.

**Comment by benjick** [comment]
Is this what we're waiting for?  #161

**Comment by benjick** [comment]
@rozenshtein @pferdefleisch Didn't help for me in a newly generated project

**Comment by Swizec** [comment]
o/

Still not working out of the box. Maybe adding the dependencies that @csbun and @pferdefleisch mentioned would be a quick fix?

**Comment by juanmnl** [comment]
Hello! ––Really want to use this component library––

I started a couple of projects yesterday, one with [CRNA](https://github.com/react-community/create-react-native-app) and the normal RN init method.

I've been getting 3-types of errors with `@shoutem/ui` while working out of the box with Native-Base and RN-Elements.

---

When I execute `yarn add @shoutem/ui`and call it from the app, I get:

<img width="373" alt="screen shot 2017-03-15 at 12 47 10 pm" src="https://cloud.githubusercontent.com/assets/699945/23965458/ca56f3f8-0996-11e7-8a76-c819810bcc49.png">

Then I `yarn add @expo/vector-icons` –to get rid of this error– but i get a new one:
(the one described in this issue ticket)

<img width="374" alt="screen shot 2017-03-15 at 2 32 02 pm" src="https://cloud.githubusercontent.com/assets/699945/23965535/ff9d33a6-0996-11e7-8df0-0588c71ffdcb.png">

I've tried everything in every github thread, including this one, without success.
Even tried to import the Fonts with [this method](https://github.com/exponent/shoutem-example/blob/master/main.js#L20-L36) without luck.
As soon as i import {Font} from exponent, i get this:

![img_2274](https://cloud.githubusercontent.com/assets/699945/23966253/6bc12766-0999-11e7-9c53-5302807e20cf.PNG)


Thanks for your help!
😄 
----
```
macOS Sierra 10.12.13 
node v7.7.2
npm 4.4.2
yarn v0.21.3
react-native-cli: 1.3.0
react-native: 0.41.2
```

**Comment by SoHotSoup** [comment]
Fixed with latest release v0.12.0

**Comment by ilarumk** [comment]
i have v0.12.0 still same issue, 
Do i need to do this ?
```
If this is a custom font, be sure to load it with Exponent.Font.loadAsync.
```

**Comment by guofoo** [comment]
I've found a workaround, where you replace the current <Icon> component from @shoutem in your code and instead use one of the icon sets from @expo/vector-icons, such as <Ionicons>

**Comment by Samueljoli** [comment]
This did the issue for me. Hopefully this helps someone.
https://github.com/oblador/react-native-vector-icons/issues/461

**Comment by wlinglinux** [comment]
fontFamily 'Rubik-Regular' is not a system font and has not been loaded through Expo.Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly andthat it is supported by your device operating system.

- If this is a custom font, be sure to load it with Expo.Font.loadAsync.
- node_modules/expo/src/Font.js:34:10 in processFontFamily
- ... 21 more stack frames from framework internals

**Comment by navotera** [comment]
no luck using the   "@shoutem/ui": "^0.23.4",

get this message on expo : 
8:52:36 PM: fontFamily 'Rubik-Regular' is not a system font and has not been loaded through Expo.Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Expo.Font.loadAsync.
- node_modules/expo/src/Font.js:34:10 in processFontFamily
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:3372:38 in diffProperties
- ... 30 more stack frames from framework internals

**Comment by Vladimir-Vdovic** [comment]
Hey guys.

If you're using expo, you have to load custom fonts asynchronously, as is shown in our example `create-react-native-app`, [here](https://github.com/shoutem/ui/blob/develop/examples/create-react-native-app/App.js).

If you're using regular `react-native init`, make sure you've successfully linked the package.

Why all this? Because fonts are loaded into the binary of the app, meaning any package with a font is considered a package with native dependencies.

**Comment by navotera** [comment]
Thanks mr @Vladimir-Vdovic seem like this problem would be disaster for noobs such as me..  hehe
