### ISSUE TITLE
NavigationBar.View is too low in RestaurantApp

### ISSUE THREAD

**Issue by evelan** [shoutem/ui#155]
I was trying to use shoutem/ui, but I noticed that navigation bar i constantly too low. So i cloned example app with restaurants. And this is result of clean build fetched from github. I'm doing something wrong or it's just a bug? 

![screen shot 2017-02-08 at 21 08 21](https://cloud.githubusercontent.com/assets/1548104/22755345/03d3c58a-ee43-11e6-9e58-b2104fba6fbe.jpg)

**Comment by ShaunSpringer** [comment]
Seeing this issue as well.

I added **marginTop: 0** to the styles for navigationBar and it resolved it

**Comment by martinezguillaume** [comment]
No, I have this problem too !

**Comment by ashemah** [comment]
I'm seeing this as well- also with the example project.

Can someone explain the steps required to fix this? How do I add this style to a navigationHeader?

**Comment by martinezguillaume** [comment]
I think that it's [here](https://github.com/shoutem/ui/blob/develop/theme.js#L1250), just put 0 to workaround this.

**Comment by zrumenjak** [comment]
Duplicate of #193
