### ISSUE TITLE
Setting backgroundColor on NavigationBar

### ISSUE THREAD

**Issue by kballenegger** [shoutem/ui#160]
As far as I can tell, there doesn't seem to be a way to set the `backgroundColor` on `navigationBar`. Setting the color of the element positioned _below_ the nav bar won't always do the trick; I'm currently needing to find a way to set the backgroundColor of the container element for the bar itself. This seems to be impossible as it's either overwritten by `white` or `transparent` depending on whether `styleName` has `clear`.

This seems to be a prevalent design decision within the framework; where it seems that a few predefined styles are provided in `styleName` with no way to override them or modify them.

**Comment by SoHotSoup** [comment]
Hey @kballenegger I believe this should do the job:
```javascript
<NavigationBar
  style={{
    container: {
       backgroundColor: 'red'
    },
  }}
```

Also, the general logic is, if you want to override any prop defined by any `styleName` you use, you can pass the inline style. Inline style would always override style defined by `styleName`. Additionally, the whole style defined by styleName of any component is placed in [theme.js] (https://github.com/shoutem/ui/blob/develop/theme.js#L1051), so when you need to override something you could it by passing inline style. If you want to write your own theme to avoid copying of the same style all your repo here are instructions on how to do it http://shoutem.github.io/docs/ui-toolkit/theme/introduction.
It's easy and it gives you the power of SCSS in RN, even NativeBase is using it in their new version.
