### ISSUE TITLE
Image overflows when I use padding on a ListView instead of a Margin

### ISSUE THREAD

**Issue by moultz** [shoutem/ui#163]
Hi,

I have a View which contains a ListView which I want to have a paddingHorizontal of 20 however when I try and do this the images inside a tile overflow.

However when the view has a marginHorizontal of 20 it does not behave like this.

Any ideas what's going on here?

![image](https://cloud.githubusercontent.com/assets/2600623/22885184/32624c90-f1f0-11e6-9d20-f54e721e401b.png)

EDIT:

Giving the Image padding or margin Left works, but doesn't on Right

**Comment by SoHotSoup** [comment]
Hey @moultz could you provide me the code snippet? I think that it could be to image styleNames, which are relative to window width or it could be because of you are passing style directly to ListView. Have you tried to pass style to list item?

**Comment by zrumenjak** [comment]
You are probably using a styleName on the image that defines exact image dimensions. If you want to cover this case, you should either pass a style with dimensions that match your parent container, or use flex rules to size your image.
