### ISSUE TITLE
HorizontalPager and TabBar

### ISSUE THREAD

**Issue by martinezguillaume** [shoutem/ui#165]
I think that we need to provide a way to display a tab bar depending of the HorizontalPager like this: 

![demo-fb](https://cloud.githubusercontent.com/assets/17292331/22953453/93435e06-f311-11e6-88c4-93a13eb76a1b.gif)

For that, the props "renderOverlay" of HorizontalPager needs to provide a function in parameter that go to the index that we specified. (```goToPage(index)``` for example).

the props "renderOverlay" need to provide too the values of the function 'OnScroll' of the ScrollView to have the liberty to add animation in the tab bar depending of the scroll values.

We can have a look in this library https://github.com/skv-headless/react-native-scrollable-tab-view

Please share if you have others ways to do it !

**Comment by SoHotSoup** [comment]
@martinezguillaume I have noticed that you are very active here, thank you for that, I will take a look at possible solutions and write it here. Also, I will include @ikalafat, who originally wrote the component into this discussion.

**Comment by martinezguillaume** [comment]
Hello ! I forked the repo here
https://github.com/martinezguillaume/ui/tree/feature/horizontalpager-tabbar
I'm working on it 😁

**Comment by SoHotSoup** [comment]
Cool! I will write down my thoughts on it here later.

**Comment by martinezguillaume** [comment]
I've made a pr here https://github.com/shoutem/ui/pull/170, I know there is a lot of enhancement but I think that it's more efficient to work from a base 😁

**Comment by ikalafat** [comment]
@SoHotSoup I've checked the PR (not-so-thorougly, yet) and wrote my comments/thoughts there, but your wisdom and thoughts will be appreciated, too :)

**Comment by Vladimir-Vdovic** [comment]
Checked PR #170, assuming this is now resolved, so I will close this thread. Prompt for re-opening if issue is still relevant.
