### ISSUE TITLE
`adjustsFontSizeToFit` on <Text> or <Heading> crashes app

### ISSUE THREAD

**Issue by JulianKingman** [shoutem/ui#167]
Placing the `adjustsFontSizeToFit` property on a shoutem Text or Heading component view instantly crashes the app with no error code. Using the react-native `Text` component works fine.

**Comment by SoHotSoup** [comment]
Hey @JulianKingman! Thank you for submitting this issue, Is this applicable on any our typo component? If you take a look at this [line](https://github.com/shoutem/ui/blob/develop/components/Text.js#L15), you will see that we pass all props to original RN component, so maybe something other causes the crash. Could you, please, give me some callstack on that?
