### ISSUE TITLE
View was rendered with explicitly set width/height but with a 0 flexBasis.

### ISSUE THREAD

**Issue by akusany2** [shoutem/ui#171]
Hi, I am getting this error : `View was rendered with explicitly set width/height but with a 0 flexBasis. (This might be fixed by changing flex: to flexGrow:) View: <RCTShadowView: 0x6080001ba780; viewName: RCTView; reactTag: 89; frame: {{0, 0}, {375, 65}}>`

I am getting this error when the data is changed **dynamically** in ListView. I am using firebase as database layer, so when a data is sync'd in my redux store it gives this error.

![simulator screen shot 18-feb-2017 7 24 49 pm](https://cloud.githubusercontent.com/assets/3200031/23094200/9b925a2e-f61a-11e6-8077-12acf933dcb3.png)

```
This works around a breaking change in css-layout where setting flexBasis needs to 
be set explicitly, instead of relying on flex to propagate.

We check for it by seeing if a width/height is provided along with a flexBasis  
of 0 and the width/height is laid out as 0.
```

This is stated in react-native code, but I need to know if @shoutem is creating this issue as I am using all render components from shoutem (ListView, View ...). 

@shoutem/ui: 0.10.8
react-native: 0.39.0

**Comment by SoHotSoup** [comment]
Hey @akusany2! I think we too had an issue with this on RN0.39.0, could you, please try to upgrade to RN0.39.2, as we surely can confirm it works with it...

**Comment by akusany2** [comment]
The reason I am using 0.39.* is because the latest version was failing at build in xCode. I'll try with the upgraded version though. Thanks!

**Comment by akusany2** [comment]
Hi @SoHotSoup, I tried the same with react-native version 0.39.2, still having the same issue.

**Comment by SoHotSoup** [comment]
Could you provide me with more details about how does your renderRow looks
like?

**Comment by tquiroga** [comment]
Still happening on RN 0.42, I'm getting that just trying to insert a full width button in my `render()`:
```
<Button styleName="full-width">
  <Text>SEE ALL COMMENTS</Text>
</Button>
```
