### ISSUE TITLE
StatusBar translucent removed

### ISSUE THREAD

**Issue by kuzyk** [shoutem/ui#174]
Why you remove translucent from NavigationBar?

https://github.com/shoutem/ui/commit/de5e30a811e397309b9cba2f375f33445dbf45fd
commit named "Fix lint errors" but from components/NavigationBar/NavigationBar.js file removed translucent prop that breaks style

**Comment by zrumenjak** [comment]
Translucent status bar caused many layout issues on a lot of Android devices. Maybe we could reintroduce it, but it shouldn't be enabled by default. Also, if you need this functionality, you could add it manually on any screen where you require it, by simply adding `<StatusBar translucent />` in your screen, all StatusBar props will be merged and applied to the status bar by RN.
