### ISSUE TITLE
Right NavigationBar Component not displaying

### ISSUE THREAD

**Issue by mosesmc52** [shoutem/ui#175]
Hi I'm testing the right NavigationBar component but it is not displaying within my view. I'm not sure if I'm doing something wrong. Below is the code I'm using to display the Nav Bar. I currently developing the app for IOS.

      <View style={{ paddingTop: 70 }}> 
         <NavigationBar
          leftComponent={<Icon name="sidebar" />}
          centerComponent={<Title>Levels</Title>}
          rightComponent={<DropDownMenu
            options={[
            { name: 'All', value: 1 },
            { name: 'Sport', value: 1 },
            { name: 'World', value: 1 },
            { name: 'Lifestyle', value: 1 },
            { name: 'Food', value: 1 },
            { name: 'Music', value: 1 },
            { name: 'Movies', value: 1 },
            { name: 'Tech', value: 1 },
            { name: 'Fun', value: 1 },
            { name: 'Fashion', value: 1 },
            ]}
            titleProperty="name"
            valueProperty="value"
          />}
                     style={{ container: { zIndex: 1 } }}
        />
      </View >

**Comment by SoHotSoup** [comment]
I think this should help you:
```javascript
<NavigationBar
      styleName="inline"
      leftComponent={<Icon name="sidebar" />}
      centerComponent={<Title>Levels</Title>}
      rightComponent={<DropDownMenu
        options={[
        { name: 'All', value: 1 },
        { name: 'Sport', value: 1 },
        { name: 'World', value: 1 },
        { name: 'Lifestyle', value: 1 },
        { name: 'Food', value: 1 },
        { name: 'Music', value: 1 },
        { name: 'Movies', value: 1 },
        { name: 'Tech', value: 1 },
        { name: 'Fun', value: 1 },
        { name: 'Fashion', value: 1 },
        ]}
        titleProperty="name"
        valueProperty="value"
      />}
    />
```

so you should add `styleName` `inline` to it. Also I would recommend to you to migrate to `CardStack` and `NavigationBar` from `@shoutem/ui/navigation` take a look for example usage at RestaurantsApp.

**Comment by asimsagirabbasi** [comment]
I put simple navigationBar and nothing comes out 
please suggest me where iam wrong
import { NavigationBar } from 'shoutem.navigation';

 <NavigationBar styleName="inline" centerComponent={<Title>TITLE</Title>}/>

**Comment by asimsagirabbasi** [comment]
> 
> 
> I think this should help you:
> 
> ```js
> <NavigationBar
>       styleName="inline"
>       leftComponent={<Icon name="sidebar" />}
>       centerComponent={<Title>Levels</Title>}
>       rightComponent={<DropDownMenu
>         options={[
>         { name: 'All', value: 1 },
>         { name: 'Sport', value: 1 },
>         { name: 'World', value: 1 },
>         { name: 'Lifestyle', value: 1 },
>         { name: 'Food', value: 1 },
>         { name: 'Music', value: 1 },
>         { name: 'Movies', value: 1 },
>         { name: 'Tech', value: 1 },
>         { name: 'Fun', value: 1 },
>         { name: 'Fashion', value: 1 },
>         ]}
>         titleProperty="name"
>         valueProperty="value"
>       />}
>     />
> ```
> 
> so you should add `styleName` `inline` to it. Also I would recommend to you to migrate to `CardStack` and `NavigationBar` from `@shoutem/ui/navigation` take a look for example usage at RestaurantsApp.

I put simple navigationBar and nothing comes out
please suggest me where iam wrong
import { NavigationBar } from 'shoutem.navigation';

<NavigationBar styleName="inline" centerComponent={<Title>TITLE</Title>}/>
