### ISSUE TITLE
Detect Device Orientation

### ISSUE THREAD

**Issue by mosesmc52** [shoutem/ui#176]
Is there any feature in Shoutem that I could use to detect the device orientation Horizontal or Vertical? 

M

**Comment by SoHotSoup** [comment]
@mosesmc52 no, there's nothing integrated to toolkit which can help you to detect device orientation. We were talking lately that would be cool to introduce something like media queries to our themes, but that left to be just an idea for now.

**Comment by mosesmc52** [comment]
Thanks. I found a RN library that that detects device orientation here. 

https://github.com/yamill/react-native-orientation

I just applied the library to my project. So far, so good.  Just thought I'd post it for any other that wants to detect orientation. 

N
