### ISSUE TITLE
NavigationBar - leftComponent doesn't get onPress event

### ISSUE THREAD

**Issue by dnish** [shoutem/ui#185]
I'm having the following customized component:

```
class NavBar extends React.Component {

    constructor(props) {
        super(props);

        this.goBack = this.goBack.bind(this);
    }

    goBack() {
        console.log('button was pressed');

    }

    render() {

        return (
                <NavigationBar
                    styleName="dark"
                    centerComponent={<Title>{this.props.title}</Title>}
                    leftComponent={<TouchableNativeFeedback onPress={this.goBack}><View><Icon name="left-arrow"/><Title>BACK</Title></View></TouchableNativeFeedback>}
                />

        );
    }
}
```

If I click on the left component, nothing happens. It seems like onPress isn't fired. I've already tested it with <code>Button</code> instead of <code>TouchableNativeFeedback</code> but this is also not working. Using <code>TouchableNativeFeedback</code> in other parts of my app works without problems.

I guess it's the same issue like this one:
https://github.com/shoutem/ui/issues/70

**Comment by zrumenjak** [comment]
Could you include an import so that I can see exactly which `NavigationBar` you are using? If you are using a navigation bar from `@shoutem/ui/navigation` then you should render the left component by using `renderLeftComponent`.
