### ISSUE TITLE
Multiple issues with version v0.10.13

### ISSUE THREAD

**Issue by rakeshgajula** [shoutem/ui#186]
Hi,

I am using shoutem ui for the first time. I was super excited when i initially discovered. I appreciate all the effort you guys are putting into this framework.

I began using v0.10.13 with react-native v0.42.0 and was checking out the Example that you guys put up. I am finding multiple issues for example Navigation Bar, gradient , horizontal pager, menu. Please look at the following screenshots. I do not have any custom styles. 

**Navigation Bar**
![image](https://cloud.githubusercontent.com/assets/1473945/23736614/5676262e-045b-11e7-9a19-0f31af15c0ad.png)

**Horizontal Pager**
![image](https://cloud.githubusercontent.com/assets/1473945/23736637/7a0baae6-045b-11e7-9c70-3970e36ed83f.png)

I want to know if i am doing something wrong.

Thanks

**Comment by SoHotSoup** [comment]
Hey @rakeshgajula,

There is a rc out, so could you please verify that this doesn't happen with new version?

```
npm install --save @shoutem/ui@rc
```

**Comment by SoHotSoup** [comment]
0.12.0 is out, please try it again on clean project. This issue could be caused because react-native-vector-icons wasn't linked right when we wasn't compatible with RN ~0.40.0
