### ISSUE TITLE
linear-gradient dependency breaks compatibility with expo / create-react-native-app

### ISSUE THREAD

**Issue by brentvatne** [shoutem/ui#188]
LinearGradient is included but lives under a different native module name. imo there should be a way to inject any components that require native dependencies rather than depending on them directly

**Comment by SoHotSoup** [comment]
@brentvatne could you suggest solution on suggestion?

**Comment by brentvatne** [comment]
@SoHotSoup - Maybe not use it directly in the lib and inject a background at callsites where it's needed, eg: with `renderBackground` for the header or something along those lines. That's a little bit annoying for you guys and shoutem users to do though.. 

I'll think about this one.

**Comment by zrumenjak** [comment]
@brentvatne why are you re-exporting native dependencies under different names? Can you make them available under their original names as well? This would allow RN libraries that are using the same dependencies to function in the CRNA environment without any changes.

Most of our UI components don't have native dependences, and they will function correctly in the expo preview app. Ejecting from the CRNA environment always remains an option for developers that really want to use those components.

**Comment by evrimfeyyaz** [comment]
@brentvatne Is there any update on this? I know it's requires some work, but @zrumenjak's solution sounds good to me.
