### ISSUE TITLE
NavigationBar. How to use it?!

### ISSUE THREAD

**Issue by X-Tender** [shoutem/ui#189]
I don't know if its me or/and what I'm doing wrong but somehow I cant even get a simple NavigationBar to run :)

That's my simple Code (Just the render part):
```
const App = () => {
	return (
		<Screen>
			<NavigationBar centerComponent={<Title>TITLE</Title>} />
		</Screen>
	);
};
```
When I launch it I get the Error:
```
undefined is not a function (evaluating 'getScene()')
```
The error is somewhere in `NavigationBar.js:62 @ setNextNavBarProps`.
I searched for that but couldn't finde anything, and the Examples are also that simple.

Are the Examples deprecated?! :/

**Comment by SoHotSoup** [comment]
Hi @X-Tender!
We have to different `NavigationBar` one from `@shoutem/ui` which is standalone component, and have an API you mentioned and one from `@shoutem/ui/navigation` which is coupled with our `CardStack` it seems that you have imported the second one and you are using it as the first one.
At the start we had only the first one and people started to use it, and later we developed the second, but we didn't want to break existing apps, so we decided to leave existing one.

**Comment by X-Tender** [comment]
Oh. What is the "better" Component?

**Comment by SoHotSoup** [comment]
There are different. The first one is navigation agnostic. It doesn't
depend on anything. It could be rendered as part of navigation system of
your choice or as a part of the screen. The second one couldn't work
without our CardStack and allows you to change global NavigationBar from
the Screen, also it gives you native transitions between navigation bar
states. To look more on how to use it, take a look at RestaurantsApp in our
examples.

**Comment by X-Tender** [comment]
Thanks a lot, I take a look at it.
Is there some kind of documentation for the `CardStack` Component?

**Comment by SoHotSoup** [comment]
It is almost the same as one from RN. I'm not sure is it documented in our
documentation, but I think RestaurantsApp is really good example of its
usage.

**Comment by X-Tender** [comment]
Ok, I guess I figure it out :)
