### ISSUE TITLE
Issues with NavigationBar

### ISSUE THREAD

**Issue by aemdy** [shoutem/ui#193]
I ran the Restaurants App example (which required me to modify `index.ios.js` and change component name to

`AppRegistry.registerComponent('ShoutemRestaurants', () => Root);`

And as a result, navigation bar seems to be faulty:
<img width="374" alt="screen shot 2017-03-15 at 00 07 32" src="https://cloud.githubusercontent.com/assets/1015018/23937184/6a77c0d0-0913-11e7-9250-3d8d5ebb4528.png">

Also, I started my own project and it seems that the problem persists - top of the scene is not visible and covered by white overlay. Navigation bar controls are on top of scene content and make it unclickable.

**Comment by zrumenjak** [comment]
I cannot reproduce this with the latest develop.
