### ISSUE TITLE
Button style is not applied

### ISSUE THREAD

**Issue by crpr** [shoutem/ui#194]
I'm trying to create a simple button in a component and it doesn't apply any style to it. I'm using the default theme. 

React_native 0.41.2

I don't have build errors.

`<Button styleName="dark">
   <Icon name="tweet" />
   <Text>SIGN IN</Text>
</Button>`

![screen shot 2017-03-15 at 11 03 34](https://cloud.githubusercontent.com/assets/989209/23945614/0f4e72f6-096f-11e7-9d01-b60474a55783.png)

**Comment by crpr** [comment]
I had previously installed NativeBase and it was making this problem. Sorry.

**Comment by eightyfive** [comment]
Hep, hi,

I'm running into the same issue, but `yarn remove native-base` + `rm -rf node_modules/` + `yarn install` + `exp start -c --localhost` (launch expo clearing the packager cache) didn't resolve the issue.

How did you get rid of the problem?
