### ISSUE TITLE
Error in installing @shoutem/ui

### ISSUE THREAD

**Issue by shukerullah** [shoutem/ui#196]
Error in installing @shoutem/ui, I am using Windows 10.

```
npm install --save @shoutem/ui@0.10.13
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:210:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:194:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:899:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit  shoutem/react-native-transformable-image#7d15395ec3857571711a12bc08f24f3a96ff1cde resetting remote C:\Users\Pir S
hukarullah Shah\AppData\Roaming\npm-cache\_git-remotes\git-github-com-shoutem-react-native-transformable-image-git-7d15395ec3857571711a1
2bc08f24f3a96ff1cde-2cd9af5f because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:210:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:194:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:899:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
```

**Comment by SoHotSoup** [comment]
Could you please try with:
```
npm install --save @shoutem/ui@rc
```

**Comment by filiphosko** [comment]
I couldn't get it installed too, but instead I didn't get any errors, the installation just got stuck on git. Installing rc helped.

**Comment by shukerullah** [comment]
@SoHotSoup I tried `npm install --save @shoutem/ui@rc` still same error, I tried on another system (windows 7) got the same error too. Is yarn required for `@shoutem/ui`?

**Comment by rockus123** [comment]
This type of development cannot be the future.  Even installation is hard.

**Comment by satishsojitra** [comment]
very very frustrated! Could not able to install it properly and even after trying command with @rc option giving same error. Why it's so hard to install?

**Comment by Jayaprakash7** [comment]
Did anyone get a solution for this?

> npm ERR! path git
> npm ERR! code ENOENT
> npm ERR! errno ENOENT
> npm ERR! syscall spawn git
> npm ERR! enoent Error while executing:
> npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/shoutem/react-native-lightbox.git
> npm ERR! enoent
> npm ERR! enoent
> npm ERR! enoent spawn git ENOENT
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent

**Comment by geraldo** [comment]
> Did anyone get a solution for this?
> 
> > npm ERR! path git
> > npm ERR! code ENOENT
> > npm ERR! errno ENOENT
> > npm ERR! syscall spawn git
> > npm ERR! enoent Error while executing:
> > npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/shoutem/react-native-lightbox.git
> > npm ERR! enoent
> > npm ERR! enoent
> > npm ERR! enoent spawn git ENOENT
> > npm ERR! enoent This is related to npm not being able to find a file.
> > npm ERR! enoent

Same error here.

**Comment by geraldo** [comment]
> Could you please try with:
> 
> ```
> npm install --save @shoutem/ui@rc
> ```

`No matching version found for @shoutem/ui@rc`

**Comment by venkateshmarappan05** [comment]
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/shoutem/react-nat
ive-lightbox.git

i got this in windows
