### ISSUE TITLE
What's happening with NavigationBar component?

### ISSUE THREAD

**Issue by yourcontainer** [shoutem/ui#203]
Clean installation
```javascript
import React, { Component } from 'react';
import { AppRegistry } from 'react-native';
import { NavigationBar, Icon, Title } from '@shoutem/ui';

export default class app extends Component {
  render() {
    return (
        <NavigationBar
            leftComponent={<Icon name="sidebar" />}
            centerComponent={<Title>TITLE</Title>}
        />
    );
  }
}

AppRegistry.registerComponent('app', () => app);
```
```
"dependencies": {
    "@shoutem/ui": "^0.12.0",
    "react": "15.4.2",
    "react-native": "0.42.3"
  },
```

Result
![3f120e1fbb](https://cloud.githubusercontent.com/assets/13626192/24176626/c2ff097e-0ea5-11e7-81ce-24b7ab34c9f3.jpg)

**Comment by yusufyildirim** [comment]
Hi,

What is the exact problem? Can you explain? So people can help you...

**Comment by kheide** [comment]
The text is out of wack compared to what the screenshots in the tutorial. Seems to be a CSS issue.

**Comment by filiphosko** [comment]
The centerComponent (in this case 'TITLE') overrides it's vertical alignment set by the parent, but the other components (leftComponent, rightComponent) don't. You can check it [here](https://github.com/shoutem/ui/blob/develop/theme.js#L1292). The parent sets 'flex-end' to all of the components, but centerComponent has 'alignSelf' set to 'center'. I think centerComponent should just comply with what the parent set on it, the question is if it is better to leave 'flex-end' or 'center' set for every component (I think 'center' looks better).

**Comment by zrumenjak** [comment]
Navigation bar issues are now fixed in develop. The fixes will be published to npm in the next version.
