### ISSUE TITLE
Grid View Layout

### ISSUE THREAD

**Issue by mgl97t** [shoutem/ui#204]
I am looking to get the Gridview that matches your Podcast image on the Gridview component page. I have attached a screenshot of what yours looks like on the left and what I am getting on the right. 

Two things: 
- How to I get the tiles evenly spaced?
- How do I make the white background full screen?

Thanks!
 
<img width="759" alt="screen shot 2017-03-21 at 10 45 07 pm" src="https://cloud.githubusercontent.com/assets/6732837/24181295/19628c14-0e88-11e7-9d75-14e04e4479dd.png">

**Comment by mgl97t** [comment]
I was able to get the white background with <Screen styleName="paper">.

**Comment by zrumenjak** [comment]
You should be able to get this layout by using `ListView`, and render a `GridRow` for each row of that list. You may also need to add some padding around the entire list content. Something like this:
```
renderRow(rowData) {
  return (
    <GridRow columns={2}>
      // your view 1
      // your view 2
    </GridRow>
  );
}

render() {
  return (
    <Screen styleName="paper">
      <ListView
        data={your data}
        renderRow={this.renderRow}
        style={{
          listContent: {
            padding: 15,
          }
        }}
      />
    </Screen>
  );
}
```

**Comment by zrumenjak** [comment]
I am closing this issue, please reopen if you have any further questions.
