### ISSUE TITLE
Default Button styling doesn't seem correct

### ISSUE THREAD

**Issue by mrbrentkelly** [shoutem/ui#215]
**react-native:** 0.43.0
**@shoutem/ui:** ^0.12.0

Just installed the shoutem/ui lib on a completely fresh React Native project and added the `<Examples />` component. When I navigate to _Buttons_ every single one is blue. I was expecting some differences between Light and Dark?

![screen shot 2017-04-04 at 14 46 56](https://cloud.githubusercontent.com/assets/5814579/24659863/dd2eccb2-1945-11e7-9f42-8aa90405c861.png)

**Comment by zrumenjak** [comment]
We are working on this, it will be fixed in the next version.

**Comment by zrumenjak** [comment]
Fixed in #217
