### ISSUE TITLE
Failed prop type: The prop `onNavigateBack` is marked as required in `App`, but its value is `undefined`.

### ISSUE THREAD

**Issue by nnemade** [shoutem/ui#220]
While trying to run Restaurent navigation-bar app in expo I am getting above error. Can someone please help with it

**Comment by zrumenjak** [comment]
Could you give us a bit more information here? Which app are you running exactly? How did you create it? A github repo that I could check out to reproduce this would be great.

**Comment by zrumenjak** [comment]
I am closing this, please reopen if the issue still exists and please include more details on how to reproduce it.
