### ISSUE TITLE
Warning: Native component for BVLinearGradient/PhotoViewAndroid does not exist

### ISSUE THREAD

**Issue by RamyElkest** [shoutem/ui#223]
Hey,

I get the following warnings for `0.12.0` using exponent

`[exp] Warning: Native component for "BVLinearGradient" does not exist`
`[exp] Warning: Native component for "PhotoViewAndroid" does not exist`

It's not an issue for me atm

**Comment by zrumenjak** [comment]
Exponent preview app doesn't support custom native dependencies. If you wish to use those components, you should properly link the `@shoutem/ui` in your app using `react-native link` and create a standalone build. More information about compatibility with CRNA and exponent can be found here: https://github.com/shoutem/ui/tree/develop/examples/create-react-native-app.

All components that don't need native dependencies should work correctly with exponent.
