### ISSUE TITLE
UNMET PEER DEPENDENCY when npm install 

### ISSUE THREAD

**Issue by llioor** [shoutem/ui#228]
I'm trying to install shoutem ui but I get some errors.

`npm install --save @shoutem/ui
`

Then I receive this error in the console:

```
+-- @shoutem/ui@0.13.0
| +-- UNMET PEER DEPENDENCY react@^15.0.0
| +-- react-native-lightbox@0.7.0  (git://github.com/shoutem/react-native-lightbox.git#4e58b9b1aca166142d69b161ff511efc3358ff9f)
| | `-- react-native-view-transformer@0.0.28  (git://github.com/ldn0x7dc/react-native-view-transformer.git#f7e028b6566022deac4e523052e74c2c63a4af7e)
| `-- react-native-transformable-image@0.0.19  (git://github.com/shoutem/react-native-transformable-image.git#7d15395ec3857571711a12bc08f24f3a96ff1cde)
`-- UNMET PEER DEPENDENCY react@16.0.0-alpha.6

npm WARN @shoutem/ui@0.13.0 requires a peer of react@^15.0.0 but none was installed.
npm WARN @shoutem/theme@0.9.0 requires a peer of react@^15.1.0 but none was installed.
npm WARN @shoutem/animation@0.10.2 requires a peer of react@^15.0.0 but none was installed.

```

The result is that I have "@shoutem" folder under node_modules with:
```
- "@shoutem"
  - animation
  - theme
  - ui
```
But the error is telling something wasn't installed.

Then I link and the response is:
`[@shoutem/ui] - linking native dependencies
`
When I'm using `"<TextInput/>"` component there are no error but there is no style as well.
Print screen is attached: https://nimbus.everhelper.me/client/notes/share/861785/e7b1kwhopz9x4mivu3g0

My package.json file look like this:
```
...
"dependencies": {
    "@shoutem/ui": "^0.13.0",
    "firebase": "^3.7.5",
    "moment": "^2.18.1",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.1",
    "react-native-device-info": "^0.10.2",
    "react-native-fcm": "^6.2.0",
    "react-native-keyboard-aware-scroll-view": "^0.2.8",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-logger": "^3.0.1",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
```
I'm using windows with android studio + avd as you can see in the print screen.
I tried with  `"@shoutem/ui": "^0.12.0"` and I have the same error.
Any idea?
Thanks, Leo.

**Comment by llioor** [comment]
This is the Example page...
https://nimbus.everhelper.me/client/notes/share/862049/421focd7mmk7lgzi0wk0
Is the the normal Input needs to look like this? (without width)

**Comment by SoHotSoup** [comment]
Hey @llioor, thank you for submitting the issue, the error at install is just npm warning because you have: `"react": "16.0.0-alpha.6",` installed which npm could not put in any range and say does it match our peerDependency range. Install went right and if linking finished successfully the right error is somewhere in `TextInput` or in your usage of the library. Could you please check does `Examples` component renders `TextInput` right in your app?

Also, could I ask you to share code snippet with me?

**Comment by llioor** [comment]
@SoHotSoup thanks for the response! 

I added a print screen in my previous comment.
Here it again: https://nimbus.everhelper.me/client/notes/share/862049/421focd7mmk7lgzi0wk0

The code is:
```
import React, { Component } from 'react';
import { AppRegistry } from 'react-native';
import { Examples } from '@shoutem/ui';

class HelloWorld extends Component {
  render() {
    return (
      <Examples />
    );
  }
}

AppRegistry.registerComponent('app', () => HelloWorld);
```

**Comment by llioor** [comment]
@Air-Miha and @SoHotSoup it looks like the link commend is working but the style is still not visible as you see in my previous comment.

I'm pretty sure the problem is with the new version of react 16 alpha 6. I need to use this version because I want to use react-native 43.
Please advice.

Thank you!

**Comment by Air-Miha** [comment]
@llioor,

Can you show us how you're using the TextInput?

If you just put it inside a _Shoutem UI Screen_ component, or a View with _flex:1_, it will work. We'll have to update the documentation and examples. But, I think that luckily this doesn't have anything to do with the version of React.

Let us know if this helps!

**Comment by llioor** [comment]
@Air-Miha 
Hey, thank you for the response.
I attached a print screen of the input text. I started a clean project and I added your example. {Example} component so actually I didn't do nothing just used your example:
```
import React, { Component } from 'react';
import { AppRegistry } from 'react-native';
import { Examples } from '@shoutem/ui';

class HelloWorld extends Component {
  render() {
    return (
      <Examples />
    );
  }
}

AppRegistry.registerComponent('app', () => HelloWorld);
```

Did shoutem ui is working with react 16 and react native 43?

**Comment by llioor** [comment]
@SoHotSoup @Air-Miha 
First I tried to wrap with a flex=1 View but is it the right style? I think it is the default of the native and not of shoutem ui as I checked in the examples.
Print screen here: https://nimbus.everhelper.me/client/notes/share/867391/seoz70de24onhstdxpu5

Second, just for your knowledge, I have the EN error in my console.. "Warning: NavigationExperimental is deprecated and will be removed in a future version of React Native."

Thank you for your support!

**Comment by Air-Miha** [comment]
@llioor,

Yes, it works. The npm warning is just a warning, and the TextInput is not stretching because the Stage component in the examples has _flexDirection:column_. If you want to see a full width TextInput in the examples, wrap it in a View that stretches itself, like this:

```
<Stage title="TextInput  / Full width secure entry" >
          <View styleName="stretch">
               <TextInput
                  placeholder="Password"
                  secureTextEntry
               />
          </View>
</Stage>
```

If you just want to use it inside your application, like in this screenshot:

https://nimbus.everhelper.me/client/notes/share/861785/e7b1kwhopz9x4mivu3g0

Wrap it in a Screen or a View with _flex:1_, like this:

```
<Screen>
  <TextInput />
</Screen>
```

You can also use a style name, like this:

```
<View styleName="flexible">
  <TextInput />
</View>
```

Just remember that the top level component needs to have its _flex_ property set. If you take a look at the HelloWorld example from React Native, you'll see the same thing. 

As for NavigationExperimental, we have plans for migration.

**Comment by llioor** [comment]
@Air-Miha 
Thanks for the detailed answer!
The full width works!

I think the problem now is with the style, Do you see the underline I have in the TextInput? This is not the right style as I see here: http://shoutem.github.io/docs/ui-toolkit/components/text-input 

This is the "green" underline: https://nimbus.everhelper.me/client/notes/share/867391/seoz70de24onhstdxpu5
What is wrong with my system?
Npm is just a warning, link works... import is correct so what do you think is the problem?
Thanks

**Comment by Air-Miha** [comment]
This is an Android specific thing. Check this issue for a solution:

https://github.com/facebook/react-native/issues/5424

**Comment by Vladimir-Vdovic** [comment]
Closing. Assuming resolved. Prompt for re-opening if issue is still relevant.
