### ISSUE TITLE
Example to set the Background of a Button as a Linear Gradient

### ISSUE THREAD

**Issue by aswinmohanme** [shoutem/ui#231]
How do I set the background of a button as a Linear Gradient ?

**Comment by SoHotSoup** [comment]
Hey @aswinmohanme there is not an official way to do it at the moment, but you can achieve it with something like this:
```javascript
<Button>
  <View
    styleName="fill-parent"
    style={{
      backgroundGradient: {
        colors: ['rgba(0, 0, 0, 0.0)', 'rgba(0, 0, 0, 0.8)'],
        locations: [0.36, 1.0],
      },
    }}
  >
    <Text>Click me!</Text>
  </View>
</Button>
```

But the right solution would be to enable `backgroundGradient` property on all container components, not only on `View` and then you would be able to set that style directly on your `Button` or even create a styleName that adds gradient by default.
If you are willing to contribute, I can write you more tips about it, if not, we can close this issue.
