### ISSUE TITLE
Typography styleNames not working

### ISSUE THREAD

**Issue by JulianKingman** [shoutem/ui#235]
I recently updated from ~v0.9 to ~v0.13, and all the styleNames seemed to have stopped working for typography elements. The most noticable is `styleName="bright"`, which no longer changes the text color. Any idea why?
![screen shot 2017-04-18 at 11 42 47 am](https://cloud.githubusercontent.com/assets/1566400/25139736/2b58b0b0-242c-11e7-95a8-52201defe4d8.png)
(Notice the dark grey text in the title, which is a `Text` component).

**Comment by SoHotSoup** [comment]
Hey @JulianKingman we have introduced a breaking change on latest release https://github.com/shoutem/ui/releases/tag/v0.13.0
Which renames "dark" and "light" style names to "secondary" and "primary".

**Comment by JulianKingman** [comment]
Thanks!

**Comment by JulianKingman** [comment]
Hang on, where's the primary style? I don't see it in the default theme.

**Comment by itanhduy** [comment]
> Hey @JulianKingman we have introduced a breaking change on latest release https://github.com/shoutem/ui/releases/tag/v0.13.0
Which renames "dark" and "light" style names to "secondary" and "primary".

Hi @SoHotSoup,

Should we update the documents as posted here?
https://shoutem.github.io/docs/ui-toolkit/components/typography#text

**Comment by Vladimir-Vdovic** [comment]
I've just [added](https://github.com/shoutem/shoutem.github.io/commit/f95a8abfd2c1dd4075e54ba20e22e05b98ded1a3) it to the typography `styleNames`.
