### ISSUE TITLE
Unrecognized font family 'rubicon-icon-font'

### ISSUE THREAD

**Issue by matheusmatos** [shoutem/ui#236]
Hi Guys, I've already tried reinstall and relink:
- `shoutem/ui`
- `react-native-vector-icons`
- `react-native-linear-gradient`

It only occurs on iOs and my project has all items in "Fonts provided by application".

Can anyone help me?

<img width="400" src="https://cloud.githubusercontent.com/assets/1237450/25182639/af81b1c4-24eb-11e7-9237-f35c2ddae50f.png"/>

**Comment by SoHotSoup** [comment]
Hey @matheusmatos, could you write me more details about you environment e.g. paste packge.json of your project here?
