### ISSUE TITLE
NavigationBar overlapping

### ISSUE THREAD

**Issue by kshmr** [shoutem/ui#237]
I have `view` :

```javascript
<Screen>
                <NavigationBar
                    leftComponent={<Icon name="sidebar" />}
                    centerComponent={<Title>TITLE</Title>}
                    styleName={'inline'}
                />
                <Title>
                     Shoutem UI
                 </Title>

            </Screen>
```

But, `NavigationBar` get overlapping :

<img width="346" alt="screen shot 2017-04-24 at 10 26 23 am" src="https://cloud.githubusercontent.com/assets/26161165/25321463/f71ec7a6-28d8-11e7-9d4f-447cfa36b694.png">
Fyi, I've used `react-native-router-flux`  with  `hideNavBar={true}` , is that the problem or i miss some setup ?

**Comment by yusufyildirim** [comment]
As you can see #104, this issue was solved. After several releases, this PR overwritten: https://github.com/shoutem/ui/commit/319ebf3faeb3f4b8fe9cd2d096d4becaaa04049e#commitcomment-21875998

So, I was know that issue but I just solved my own issue and didn't send a PR but I will today.

**Comment by yusufyildirim** [comment]
I sent a PR #239.
