### ISSUE TITLE
Padding left on Button

### ISSUE THREAD

**Issue by martinezguillaume** [shoutem/ui#238]
Hey,

I notice that my Button have an unexpected behavior

![image](https://cloud.githubusercontent.com/assets/17292331/25331567/d01afe12-28e3-11e7-8693-2c52a4932c1b.png)

You can see that the View inside the button has a paddingLeft of 15

![image](https://cloud.githubusercontent.com/assets/17292331/25331541/bfe2dd6c-28e3-11e7-84af-2cce3a227273.png)

My Button component looks like this

```js
      $(Button, { onPress: retry },
        $(Icon, { name: 'refresh' }),
        $(Text, null, 'Reload'),
      ),
```

**Comment by SoHotSoup** [comment]
Hey @martinezguillaume do you have a custom theme in your app?

**Comment by martinezguillaume** [comment]
No I have juste the shoutem ui theme... (```import { getTheme } from '@shoutem/ui';```)
Don't know what's wrong.. I have @shoutem/ui 0.13.0

**Comment by SoHotSoup** [comment]
Could you check does it render right in examples component? and also, could you post the code of whole screen here?

**Comment by Vladimir-Vdovic** [comment]
Closed for inactivity.

**Comment by JulianKingman** [comment]
I'm having the same problem. Here's what it looks like:

<img width="224" alt="screen shot 2017-10-03 at 4 01 45 pm" src="https://user-images.githubusercontent.com/1566400/31146289-2c43e844-a854-11e7-8de5-733609a0b4ed.png">

Code:
```jsx
<Button
      styleName="md-gutter-bottom"
      onPress={() => {
        Linking.openURL("App-Prefs:root=WIFI");
        setTimeout(() => this.setState({ connected: true }), 2000);
      }}
  >
    <Text>Go to Settings</Text>
</Button>
```
custom theme: 
```javascript
'shoutem.ui.Button': {
    ...defaultTheme['shoutem.ui.Button'],
    backgroundColor: colors.secondaryRed,
    paddingLeft: 10,
    paddingRight: 10,
    height: 50,
    borderRadius: 5,
    borderWidth: 2.5,
    borderColor: 'transparent',
    width: '60%',
    alignSelf: 'center',
    'shoutem.ui.Text': {
      ...defaultTheme['shoutem.ui.Button']['shoutem.ui.Text'],
      fontFamily: 'Montserrat-Regular',
      color: colors.white,
      fontSize: 15 * ratioX,
      marginHorizontal: 10,
    },
```

I can't see where the odd padding is even being set. If I inspect the button and the text, neither have the padding, it's in some intermediate component...

**Comment by JulianKingman** [comment]
Experimenting with the different views wrapping it, it only seems affected when wrapped by multiple `<View>` components
```javascript
<View styleName="fill-parent vertical space-between xl-gutter-top h-center sm-gutter-bottom">
  <View>{...button}</View>
</View>
```

**Comment by JulianKingman** [comment]
If I set the width of the inner view to '100%' then it works...
