### ISSUE TITLE
React Native 0.44 Incompatible

### ISSUE THREAD

**Issue by darkredz** [shoutem/ui#244]
RN 0.44 introduced a breaking change that makes this library incompatible with it. CustomComponents had been removed from RN

Remove CustomComponents folder and license (777e80a) - https://github.com/facebook/react-native/releases

**Comment by aswinmohanme** [comment]
In the meantime should we downgrade to RN 43 ?

**Comment by Vladimir-Vdovic** [comment]
The current workaround (until we update the UI toolkit) is to set up dependencies for your project (and reinstall node modules) as described by user dobrienlzd: 

https://github.com/shoutem/ui/issues/241#issuecomment-298602614.

Marking this issue as a duplicate of https://github.com/shoutem/ui/issues/241 and closing it.

Please reference mentioned issue for future updates.
