### ISSUE TITLE
Use Image component,RN warn this: 'invalid props.style key '0' supplied to 'image''

### ISSUE THREAD

**Issue by hxqbeyond** [shoutem/ui#248]
Use Image component,RN warn this: 'invalid props.style key '0' supplied to 'image''
RN version: 0.43.4
IOS: 10.0
![image](https://cloud.githubusercontent.com/assets/10892272/25796924/f0e538b2-340d-11e7-9d7a-3d01aa234b2b.png)

**Comment by JulianKingman** [comment]
Style doesn't support arrays, so either destructure (`{...style1, ...style2}`) or move everything into a theme.

**Comment by Vladimir-Vdovic** [comment]
Considering this resolved because no further comments were made. Closing issue.
