### ISSUE TITLE
RichMedia does not updated body when state changes

### ISSUE THREAD

**Issue by seblau** [shoutem/ui#253]
I do have the following setup. The `appSettings.login_text` has an initialize value, and gets updated as the `props` change. The problem is that the `RichMedia` component is not updating its body. When I change the `RichMedia` component part to `<Text>{appSettings.login_text}</Text>` it works as expected.

```
constructor(props, contex) {
    super(props, contex);

    this.state = {
      appSettings: {
        'login_text': 'hello',
      },
    };
}

componentWillReceiveProps(newProps) {
    if (newProps.appSettings !== this.props.appSettings) {
      const { appSettings } = newProps;
      this.setState({ appSettings: appSettings });
    }
}

render() {
  ...
  const { appSettings } = this.state;
  <RichMedia body={appSettings.login_text} />
  ...
}
```

**Comment by Vladimir-Vdovic** [comment]
RichMedia is being replaced by the [HTML component](https://github.com/shoutem/ui/tree/develop/html), so we're closing this thread. If this is still relevant with the HTML component, please prompt for reopen.
