### ISSUE TITLE
can npm install

### ISSUE THREAD

**Issue by xiaozhouwu** [shoutem/ui#256]
why I can not install this package? I am in china.

**Comment by xiaozhouwu** [comment]
I make sure the network is OK, I can install other packages.

**Comment by Vladimir-Vdovic** [comment]
What error does your terminal give you when you attempt to install the package?

**Comment by Vladimir-Vdovic** [comment]
Closing issue because of lack of info and no response.

**Comment by walter0331** [comment]
Hi @Vladimir-Vdovic, I cant install too

I got stuck here:

➜  rn-expo-project git:(master) ✗ npm -v
5.0.3
➜  rn-expo-project git:(master) ✗ npm install --save @shoutem/ui
⸨░░░░░░░░░░░░░░░░░░⸩ ⠏ fetchMetadata: sill resolveWithNewModule @shoutem/ui@0.15.0 checking installable status
