### ISSUE TITLE
How to disable sticky NavigationBar

### ISSUE THREAD

**Issue by rothanachoun** [shoutem/ui#259]
As in RestaurantDetails of RestaurantApp example I want show transparent NavigationBar. But when I scroll to the bottom of page the NavigationBar displays. 

<img width="405" alt="hide-navigation-bar" src="https://cloud.githubusercontent.com/assets/5331630/26363130/5a2abf38-400a-11e7-84d7-045ecd951660.png">

Is it possible or not to display transparent NavigationBar all the time even when scroll to the bottom?

Thanks,
Rothana

**Comment by SoHotSoup** [comment]
Hey @rothanachoun, just remove `animationName` prop, it defines scrolling animation which changes the style of the `NavigationBar`

**Comment by rothanachoun** [comment]
@SoHotSoup great thanks. it works.
