### ISSUE TITLE
What is the name of this icon?

### ISSUE THREAD

**Issue by watadarkstar** [shoutem/ui#261]
![screen shot 2017-05-27 at 4 30 53 pm](https://cloud.githubusercontent.com/assets/3059371/26524220/ff4263da-42f9-11e7-976c-d6fcfedb5f16.png)

On this [page](http://shoutem.github.io/docs/ui-toolkit/components/icons) they show the above icon but its name is not shown in the examples and I don't know what its called. Any ideas?

**Comment by Vladimir-Vdovic** [comment]
`<Icon name="rss-feed" />`

We'll work on updating our Icon documentation, we're aware some of the names listed there are outdated and some of our new icons aren't listed at all.
