### ISSUE TITLE
create-react-native-app not working with shoutem-ui

### ISSUE THREAD

**Issue by jackverstappen** [shoutem/ui#262]
Steps to reproduce:
```
$ npm install -g create-react-native-app
$ create-react-native-app my-app
$ cd my-app
$ yarn add @shoutem-ui
```

Introduce the fix to eliminate ExperimentalNavigation

Replace App.js with 
```
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import { Font, AppLoading} from 'expo';
import { Title,Caption } from '@shoutem/ui';

export default class App extends React.Component {
  state = {
      fontsLoaded: false,
    };

  async componentWillMount() {
    await Font.loadAsync({
      'Rubik-Black': require('./node_modules/@shoutem/ui/fonts/Rubik-Black.ttf'),
      'Rubik-BlackItalic': require('./node_modules/@shoutem/ui/fonts/Rubik-BlackItalic.ttf'),
      'Rubik-Bold': require('./node_modules/@shoutem/ui/fonts/Rubik-Bold.ttf'),
      'Rubik-BoldItalic': require('./node_modules/@shoutem/ui/fonts/Rubik-BoldItalic.ttf'),
      'Rubik-Italic': require('./node_modules/@shoutem/ui/fonts/Rubik-Italic.ttf'),
      'Rubik-Light': require('./node_modules/@shoutem/ui/fonts/Rubik-Light.ttf'),
      'Rubik-LightItalic': require('./node_modules/@shoutem/ui/fonts/Rubik-LightItalic.ttf'),
      'Rubik-Medium': require('./node_modules/@shoutem/ui/fonts/Rubik-Medium.ttf'),
      'Rubik-MediumItalic': require('./node_modules/@shoutem/ui/fonts/Rubik-MediumItalic.ttf'),
      'Rubik-Regular': require('./node_modules/@shoutem/ui/fonts/Rubik-Regular.ttf'),
      'rubicon-icon-font': require('./node_modules/@shoutem/ui/fonts/rubicon-icon-font.ttf'),
    });

    this.setState({fontsLoaded: true});
  }

  render() {
    if (!this.state.fontsLoaded) {
      return <View><Text>Loading</Text></View>;
    }
    return (
      <View style={styles.container}>
        <Title>CRNA</Title>
        <Caption>with shoutem-ui</Caption>
        <Text style={{ fontFamily: 'Rubik-Light', fontSize: 14 }}>Open up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Start with 
```
yarn start
```

Error Message 
```
this.updater.enqueueCallBack is not a function. (In 'this.updater.enqueueCallback(this,callback,'setState')','this.update.enqueueCallback' is undefined)
```

**Comment by Vladimir-Vdovic** [comment]
We haven't updated @shoutem/ui **yet** to stop using NavigationExperimental, so you won't be able to:
`Introduce the fix to eliminate ExperimentalNavigation` as you stated. Or are you referring to simply managing your dependencies to use RN 0.43.4?

**Comment by Panthro** [comment]
any workaround for now?

**Comment by dhirajbajaj** [comment]
Any update on this?

**Comment by atinder** [comment]
was thinking of using UI with expo. Doesn't seem to be possible right now

**Comment by rockus123** [comment]
This shoutem ui stuff is so hard to use.  It should be simple.

**Comment by cloudonshore** [comment]
Was also hoping to use UI with expo. Very excited for a fix on this, or any suggestions of a work around.

**Comment by escalepion** [comment]
Can't we use shoutem with expo right now?

**Comment by crivera** [comment]
same here... any update?

**Comment by fzymek** [comment]
+1

**Comment by Vladimir-Vdovic** [comment]
I've attempted to replicate this, using these steps:

1) `npm i -g create-react-native-app`
2) `create-react-native-app UI_Test`
3) `cd UI_Test`
4) `yarn add @shoutem/ui`
5) Replaced `UI_Test/App.js` with the code provided in the start of the issue by @jackverstappen 
6) `yarn start`
7) `i` to start on iOS emulator

Result:
<img width="394" alt="screen shot 2017-08-31 at 13 26 16" src="https://user-images.githubusercontent.com/28015757/29920997-55ef396e-8e50-11e7-813e-80e726d38175.png">

The font changed to the fonts specified in the code provided, as well as used the UI toolkit `<Title>` and `<Caption>` components

Can you confirm whether or not this is still an issue?

Furthermore, if there's something else that's an issue, please create another Issue here on Github for the UI toolkit repository and we'll take a look.

**Comment by crivera** [comment]
just tried in expo and seems to work fine now!

**Comment by Panthro** [comment]
confirmed it works, it's not a bug anymore, I believe this issue can be now closed.

Thanks for taking a look into this, I don't know if was a change on shoutem or react itself, but now it works :-)

**Comment by brunoandradebr** [comment]
It's not working if you use a shoutem Button. It dosn't preload font the way you preload in your modified main.js. sad.

**Comment by brunoandradebr** [comment]
this way : 

<Button>
    <Icon name='add-event' />
    <Text> Start </Text>
</Button>
