### ISSUE TITLE
Error in photo-view

### ISSUE THREAD

**Issue by weijianfeng** [shoutem/ui#276]
Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░  88.5% (842/895)...(node:36983) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1720): UnableToResolveError: Unable to resolve module `react-native/Libraries/Components/View/ViewPropTypes` from `/Users/weijianfeng/Work/huoban-rn-js/node_modules/react-native-photo-view/PhotoView.android.js`: Module does not exist in the module map or in these directories:
  /Users/weijianfeng/Work/huoban-rn-js/node_modules/react-native/Libraries/Components/View
,   /Users/weijianfeng/Work/node_modules/react-native/Libraries/Components/View
the reason is [react-native-photo-view/issues/67](https://github.com/alwx/react-native-photo-view/issues/67)

shoutem ui use react-native-photo-view.
but it is imported by github url.
"repository": {
    "type": "git",
    "url": "git://github.com/alwx/react-native-photo-view.git"
  },

I think it's not a good way. I suggest to use version code to manage all the dependencies.

**Comment by SoHotSoup** [comment]
Hey @weijianfeng! Could you please tell me what version of @shoutem/ui are you using? Few days ago we have published 0.16.0 on npm and it uses `react-native-photo-view 1.2.1`

**Comment by weijianfeng** [comment]
0.14.0

**Comment by weijianfeng** [comment]
in 0.16, the problem has been solved.
Thanks!
