### ISSUE TITLE
shoutem platform isn't working on android

### ISSUE THREAD

**Issue by ahmed3awd** [shoutem/ui#279]
I am trying to get started with building apps with shoutem so I've used the builder to create a sample events app then used the shoutem cli `shoutem run `to view the app's feel on ios and android using shoutem preview app. when I scan the qr code using the ios app it works fine. However, on android it renders a 
> Requiring uknown module"react-native/"
![whatsapp image 2017-07-01 at 6 13 58 pm](https://user-images.githubusercontent.com/20523742/27763748-f147ac44-5e89-11e7-9a87-80a291004cd4.jpeg)

So I've tried using it locally on my windows machine after I've setup the development environment, when I try using `shoutem run-android` the error indicates something related to `hr.apps.n13773/com.shoutemapp.MainActivity`
![capture](https://user-images.githubusercontent.com/20523742/27763770-785effa2-5e8a-11e7-9549-b9409ae00d78.PNG)
 
I've ran multiple rn apps and they work completely fine on both the emulator and a connected device. I've tried shoutem apps with both a connected android device and the emulator and neither of them seems to work.

**Comment by Vladimir-Vdovic** [comment]
Make sure your app is using the 1.0.27 platform. `react-native-photo-view` introduced a breaking change with a minor update (which shouldn't be done) and it caused issues for apps that used it. We've since resolved it with the 1.0.27 platform.

**Comment by ahmed3awd** [comment]
how can I make sure of that exactly?
