### ISSUE TITLE
scrollTo in `ListView`

### ISSUE THREAD

**Issue by davidvuong** [shoutem/ui#286]
I've added a way to scroll to the top of the list whilst using shoutem.ui but I'm not too happy with my implementation. I think I'm depending on an implementation detail and I want to know if there's a better way.

https://github.com/davidvuong/ddfa-app/blob/master/app/screens/FeedScreen/components/FeedComponent.js#L68-L86

```js
  /* Pull `listView` from shoutem.ui.ListView to `scrollTo` top. */
  onScrollToTop() {
    const scrollTo = { x: 0, y: 0, animated: true };

    // `ref` on our custom InfiniteScrollFeedCaller.
    const callerRefs = this.refs.InfiniteScrollFeedCaller.refs;

    // `InfiniteScrollFeed` is a ref in our custom wrapper.
    // `wrapperInstance` is something exposed by shoutem.ui to access the underlying
    // `ReactNative.ListView`. From there we simply call RN's `scrollTo` function.
    const wrapper = callerRefs.InfiniteScrollFeed.wrappedInstance;

    // Make sure this doesn't blow up, causing our app to potentially crash.
    if (!wrapper) {
      console.error('wrappedInstance in InfiniteScrollFeed (ListView) does not exist');
      return null;
    }
    wrapper.listView.scrollTo(scrollTo);
  }
```

I'm using `ListView` inside my own component called `InfiniteScrollFeed`:

https://github.com/davidvuong/ddfa-app/blob/master/app/screens/FeedScreen/components/InfiniteScrollFeed.js#L125-L133

```js
    return (
      <ListView
        data={checkIns}
        loading={isLoading}
        renderRow={this.renderRow}
        onLoadMore={this.onLoadMore}
        onRefresh={this.onRefresh}
        ref="InfiniteScrollFeed"
      />
    );
```

The way this works is:

1. I have a `ref` on `InfiniteScollFeed` which from there I can access the ref on `ListView`
1. Once I have `ListView` I can access the `wrappedInstance` exposed by shoutem (in this case is React Native's `ListView`)
1. After that I use the recommended `scrollTo` function to scroll to the top

This works, but is there a better approach to this?

**Comment by zrumenjak** [comment]
It is ok to do it like this at the moment. We have actually exposed certain scroll methods in the latest version, so you should be able to do this more easily now. See: https://github.com/shoutem/ui/blob/develop/components/ListView.js#L325. It should be enough to do something like this:
```
listView.scrollTo(...)
```
if a `listView` is a ref to the `ListView` component from `@shoutem/ui`.

In future versions we plan to automatically hoist all instance methods, so it should be possible to call any RN method directly on refs to our components, without the need to use `wrappedInstance`.
