### ISSUE TITLE
NavigationBar don't work

### ISSUE THREAD

**Issue by Lowisoft** [shoutem/ui#287]
Hi all,

I have started to develop with shoutem and i'm trying to understand  the philosophy behind shoutem.
I try to use a NavigationBar and therefor I have imported the navigationbar from @shoutem/ui.

Here is the code:

```
import {
  Button,
  Icons,
  Typography,
  NavigationBar
} from '@shoutem/ui';


export default class mainscreen extends Component {
  render() {
    return (
      <View style = {styles.container}>
        <NavigationBar
          centerComponent={<Title>Text</Title>}
        />
        <Text sytle={styles.text}>Hello World</Text>
        <Button>
          <Text sytle={styles.text}>Click me!</Text>
        </Button>
      </View>
    );
  }
}
```

If I push this code to the builder, the app stop working. If I change the centerComponent into `<Title>Text</Title>` the NavigationBar works.
Here the code:
```
import {
  Button,
  Icons,
  Typography,
  NavigationBar
} from '@shoutem/ui';


export default class mainscreen extends Component {
  render() {
    return (
      <View style = {styles.container}>
        <NavigationBar title ="Text"
        />
        <Text sytle={styles.text}>Hello World</Text>
        <Button>
          <Text sytle={styles.text}>Click me!</Text>
        </Button>
      </View>
    );
  }
}
```

Can someone explain me why it don't work in the first code example.

Thanks

**Comment by Vladimir-Vdovic** [comment]
The issue is that you're importing `Typography` instead of `Title`:
```
import {
  Button,
  Icons,
  Typography, <-
  NavigationBar
} from '@shoutem/ui';
```

`Typography` is not a component, it's just what we call the section on the UI Toolkit. The components are:
`Heading`, `Title`, `Subtitle`, `Text` and `Caption`.

**Comment by Lowisoft** [comment]
@Vladimir-Vdovic 

Thanks for your fast answer.
I have misinterpreted the component Typography. It's not really a component (as it is mentioned on the developer Webpage, but a generic term for predefined styles.

So I have add Title as component in the import section from @shoutem/ui, but this change nothing, the app still stop running without any error message. I have launched the app with shoutem run --dev for debugging, but no error is shown.

Here the modified code:

import React, {
  Component
} from 'react';

import {
  StyleSheet,
  View,
  Text
} from 'react-native';

import {
  Button,
  Icons,
  Title,
  NavigationBar
} from '@shoutem/ui';


export default class mainscreen extends Component {
  render() {
    return (
      <View style = {styles.container}>
        <NavigationBar 
          centerComponent={<Title>EasyFood</Title>}
           //rightComponent={} 
        />
        <Text sytle={styles.text}>Hello World</Text>
        <Button>
            <Text sytle={styles.text}>Click me!</Text>
        </Button>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    fontSize: 20,
  },
});

**Comment by Lowisoft** [comment]
sorry, copy paste hasn't worked.

import React, {
  Component
} from 'react';

import {
  StyleSheet,
  View,
  Text
} from 'react-native';

import {
  Button,
  Icons,
  Title,
  NavigationBar
} from '@shoutem/ui';


export default class mainscreen extends Component {
  render() {
    return (
      <View style = {styles.container}>
        <NavigationBar 
          centerComponent={<Title>EasyFood</Title>}
           //rightComponent={} 
        />
        <Text sytle={styles.text}>Hello World</Text>
        <Button>
            <Text sytle={styles.text}>Click me!</Text>
        </Button>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    fontSize: 20,
  },
});

**Comment by Lowisoft** [comment]
Sorry, copy paste hasn't worked,
`import React, {
  Component
} from 'react';

import {
  StyleSheet,
  View,
  Text
} from 'react-native';

import {
  Button,
  Icons,
  Title,
  NavigationBar
} from '@shoutem/ui';


export default class mainscreen extends Component {
  render() {
    return (
      <View style = {styles.container}>
        <NavigationBar 
          centerComponent={<Title>EasyFood</Title>}
           //rightComponent={} 
        />
        <Text sytle={styles.text}>Hello World</Text>
        <Button>
            <Text sytle={styles.text}>Click me!</Text>
        </Button>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    fontSize: 20,
  },
});
`

**Comment by Lowisoft** [comment]
Sorry copy paste hasn't worked correctly,

`import React, {
  Component
} from 'react';

import {
  StyleSheet,
  View,
  Text
} from 'react-native';

import {
  Button,
  Icons,
  Title,
  NavigationBar
} from '@shoutem/ui';


export default class mainscreen extends Component {
  render() {
    return (
      <View style = {styles.container}>
        <NavigationBar 
          centerComponent={<Title>EasyFood</Title>}
           //rightComponent={} 
        />
        <Text sytle={styles.text}>Hello World</Text>
        <Button>
            <Text sytle={styles.text}>Click me!</Text>
        </Button>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    fontSize: 20,
  },
});
`

**Comment by Lowisoft** [comment]
import React, {
  Component
} from 'react';

import {
  StyleSheet,
  View,
  Text
} from 'react-native';

import {
  Button,
  Icons,
  Title,
  NavigationBar
} from '@shoutem/ui';


export default class mainscreen extends Component {
  render() {
    return (
      <View style = {styles.container}>
        <NavigationBar 
          centerComponent={<Title>EasyFood</Title>}
           //rightComponent={} 
        />
        <Text sytle={styles.text}>Hello World</Text>
        <Button>
            <Text sytle={styles.text}>Click me!</Text>
        </Button>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    fontSize: 20,
  },
});

**Comment by Vladimir-Vdovic** [comment]
I can't reproduce your issue. I've tried `shoutem run`, `shoutem run-ios` and `shoutem run-android`. The code you've given me works fine on all of them.

Here's a screenshot from `shoutem run-ios`:
![screen shot 2017-07-12 at 11 02 36](https://user-images.githubusercontent.com/28015757/28110133-b01f03be-66f1-11e7-90e0-220e20510bf3.png)

I don't know how to help you further without some sort of error or additional info.

**Comment by SoHotSoup** [comment]
@Lowisoft as I have understand you are working on extensions.

`NavigationBar` you are using is an inline component, to be used outside our extensions or in special cases. Extension screens are navigated by our shoutem.navigation extension which provide you an implementation of main navigation layouts (Tab bar, drawer, list, grid...).

The code for your screen should look like this
```javascript
import React, {
  Component
} from 'react';

import {
  StyleSheet,
  View,
  Text
} from 'react-native';

import {
  Button,
  Icons,
  Title,
} from '@shoutem/ui';

import { NavigationBar } from '@shoutem/ui/navigation';

export default class mainscreen extends Component {
  render() {
    return (
      <View style = {styles.container}>
        <NavigationBar 
          centerComponent={<Title>Text</Title>}
        />
        <Text sytle={styles.text}>Hello World</Text>
        <Button>
            <Text sytle={styles.text}>Click me!</Text>
        </Button>
      </View>
    );
  }
}
```
Follow these tutorial to get more info
http://shoutem.github.io/docs/extensions/my-first-extension/using-ui-toolkit

**Comment by Lowisoft** [comment]
Thanks SoHotSoup for your help,

The extension runs now, but I can't see the title in the top of the screen.

![image](https://user-images.githubusercontent.com/30078772/28170647-58445efa-67e6-11e7-9457-f4791576c0a1.png)

**Comment by SoHotSoup** [comment]
Sorry, I forgot to change the code of the `NavigationBar`

```
<NavigationBar 
    title="Text"
/>
```
