### ISSUE TITLE
Avatar-medium resize not round

### ISSUE THREAD

**Issue by eightyfive** [shoutem/ui#289]
Hi,

When I apply `<Image source={{ uri }} styleName="medium-avatar" />` I don't get a rounded image, but more of a Losange one...

![screen shot 2017-07-14 at 18 59 30](https://user-images.githubusercontent.com/3809074/28211431-d385e7f6-68c6-11e7-8c3f-e1d8fc51b00b.png)

The original image is not squared, but from my understanding reading the docs, it shouldn't matter.

Additional notes:
- I am using the iOS Simulator
- Photo taken from default "Photo Library" of iOS Simulator

**Comment by Vladimir-Vdovic** [comment]
Testing with UI toolkit version 0.21.3, cannot seem to reproduce.

Code:
```
render() {
    return (
      <Screen styleName="horizontal h-center">
          <Image source={{ uri: "https://blog.shoutem.com/wp-content/uploads/2016/09/Shoutem-logo-1.png" }} styleName="medium-avatar" />
      </Screen>
    );
  }
```
Where the image provided is 351x197px. Produces:
![screen shot 2017-09-07 at 13 11 27](https://user-images.githubusercontent.com/28015757/30160744-15d19e34-93ce-11e7-93ca-96ee8019cfe2.png)


Issue seems to be resolved, prompt for reopen if issue persists with newest UI toolkit.
