### ISSUE TITLE
Fontawesome icons?

### ISSUE THREAD

**Issue by shakdoesgithub** [shoutem/ui#29]
are there any plans of adding fontawesome icons?

**Comment by SoHotSoup** [comment]
we have react-native-vector-icons as a dependency, so I assume that Fontawesome icons are available by default, you just have to `import Icon from 'react-native-vector-icons/FontAwesome';`

**Comment by pewh** [comment]
`Icon` which is imported from `react-native-vector-icons/FontAwesome` don't have some properties like 'styleName'. Any idea to extends this property?

**Comment by SoHotSoup** [comment]
@pewh if you connect it with `connectStyle('shoutem.ui.Icon')(FontawesomeIcon)` you will inherit all styleNames and all the style from `shoutem.ui.Icon` but you would be able of using Font Awesome icons. Take a look at https://github.com/shoutem/ui/blob/develop/components/Icon/Icon.js

**Comment by pewh** [comment]
Thanks. It's work :beers:
