### ISSUE TITLE
Android doesn't open any build in the shoutem app

### ISSUE THREAD

**Issue by Lowisoft** [shoutem/ui#292]
Trying to launch a build in the shoutem preview app on Android, I receive following error: 'Unfortunately Shoutem has stopped'. The build is a very simple build, outgoing from a blank app to which I have added the place extension. That's all. Then I have simply scanned the QR in the Shoutem preview app, which has as result the above mentioned error.

Thanks for your help.

**Comment by Vladimir-Vdovic** [comment]
The @shoutem/ui repository isn't an appropriate place for this inquiry. Contact Shoutem's support via e-mail.

Closing this issue.
