### ISSUE TITLE
Shoutem clone

### ISSUE THREAD

**Issue by Lowisoft** [shoutem/ui#294]
Hi, 

I have updated the cli from shoutem to the last version. Both commands Shoutem run-android or shoutem run-ios are no longer supported, From now on you have the possibility to download a copy of the code with the command "clone".

Well I have tried to use the command with a real simple App. I have created an extension with only the "Hello World" example. In the shoutem builder I have link the extension to a new app called 'Local Test".

Unfortunately the command "shoutem clone" doesn't work. The command stops coincidentally by trying to download a shoutem extension. Please look at the attached image.

![image](https://user-images.githubusercontent.com/30078772/28706787-f818a39c-7375-11e7-8791-d13ff2cb6958.png)

Thanks for any hint to solve the problem.

**Comment by Vladimir-Vdovic** [comment]
I would assume it was a network issue on your side. Please comment/edit the post so other users could possibly find more info here.

**Comment by SoHotSoup** [comment]
Also, I would say that this issue doesn't belog on this repo, but on https://github.com/shoutem/cli
