### ISSUE TITLE
Cannot use Shoutem's style names

### ISSUE THREAD

**Issue by luisbajana** [shoutem/ui#307]
Hi guys, thank you for this amazing components. I've been dealing with a problem for few hours. I cannot "load" the proper Shoutem's styles.

For example:
I'm trying to set the styleName="dark" to a button, but I'm getting the same result as if I leave it without any styleName. 

As you can see in the image below, the button style is wrong. Also the button overlaps the NavigationBar, I'm a little bit confused over this.

![screen shot 2017-08-29 at 11 13 53 am](https://user-images.githubusercontent.com/1069185/29832611-69d5624e-8cae-11e7-995d-1227992aef7b.png)

The code:
`<Screen styleName="paper">

          <NavigationBar title="hola" />

          <Button styleName="dark">
            <Text>CHECK IN HERE</Text>
          </Button>

          </Screen>`

The includes:
`import {
  ScrollView,
  Icon,
  Row,
  Button,
  Subtitle,
  Text,
  Title,
  View,
  Image,
  Divider,
  Tile,
  Screen,
  NavigationBar
} from '@shoutem/ui';`

This is my package.json if is necessary: 
   "@shoutem/ui": "^0.21.3",
    "firebase": "^4.1.3",
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.4",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-image-picker": "^0.26.4",
    "react-native-linear-gradient": "^2.3.0",
    "react-native-vector-icons": "^4.3.0",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2"

Thank you in advance.

**Comment by Vladimir-Vdovic** [comment]
It's slightly outdated, we're working on updating the docs.

Using `secondary` instead of `dark` will give you the desired style.

**Comment by luisbajana** [comment]
@Vladimir-Vdovic  Thank you, that worked. Until which version I have to downgrade to match it with the docs? 

Do you have an Idea why my button component is going above the NavigationBar?
![screen shot 2017-08-29 at 12 48 45 pm](https://user-images.githubusercontent.com/1069185/29835732-7fae9630-8cb8-11e7-91f5-ebe676a55e04.png)

Thank you for the quick response.

Best,
Luis

**Comment by Vladimir-Vdovic** [comment]
Sorry, I'm not sure I understand what you're referring to, version of what for what to work?

How did you structure your whole screen's code? There may be an issue with structuring that's causing the button to render at the top instead of undearneath the `NavigationBar`

**Comment by luisbajana** [comment]
Hi @Vladimir-Vdovic You said that the docs are outdated, so I wanted to know if there's a version of the code that matched with the docs that are published. 

ii) This is the structure:
`<Screen styleName="paper">

          <NavigationBar title="hola" />

          <Button styleName="dark">
            <Text>CHECK IN HERE</Text>
          </Button>

       </Screen>`

Thanks!

**Comment by Vladimir-Vdovic** [comment]
I can't see the start of the `<Screen>` component, but I'm assuming it doesn't have `styleName="vertical h-center"` or anything along those lines to enforce vertical distribution of components render inside of it.

For the most part the docs will line up with what you're using, there's only a few examples and styleNames that aren't up to date, but we're working on that.

**Comment by luisbajana** [comment]
@Vladimir-Vdovic thanks, but I'm getting the  same result:

`<Screen styleName="vertical h-center">

          <NavigationBar title="hola" />

          <Button styleName="dark">
            <Text>CHECK IN HERE</Text>
          </Button>

          </Screen>`

**Comment by Vladimir-Vdovic** [comment]
Add `styleName="inline"` to your `NavigationBar`. That worked for me.

Code:
```
render() {
    return (
      <Screen>
        <NavigationBar title="hola" styleName="inline" />
        <Button styleName="secondary">
          <Text>CHECK IN HERE</Text>
        </Button>
      </Screen>
    );
  }
```

Resulting with:
![screen shot 2017-08-30 at 10 17 12](https://user-images.githubusercontent.com/28015757/29862316-8b973498-8d6c-11e7-8c2d-9526f1e3ee37.png)

**Comment by Vladimir-Vdovic** [comment]
Issue seems to be resolved, closing it.
