### ISSUE TITLE
Example for React Navigation

### ISSUE THREAD

**Issue by pedzed** [shoutem/ui#309]
Can somebody explain how this can work with React Navigation? I am not sure how this can work together.

I believe this is relevant: https://reactnavigation.org/docs/navigators/custom

Is it possible that this will be supported out of the box?

**Comment by Vladimir-Vdovic** [comment]
Similar inquiry as [this issue](https://github.com/shoutem/ui/issues/311#issuecomment-328476880). Answer can be found in comment.

More info about creating customized components can be found [here](http://shoutem.github.io/docs/ui-toolkit/theme/introduction#building-customizable-components).
