### ISSUE TITLE
React Navigation integration - are you guys still working on it?

### ISSUE THREAD

**Issue by andreimc** [shoutem/ui#311]
I am building a project and I want to use shoutem/ui, I already use react-navigation and I am just thinking of wrapping the components with a shoutem theme. 

I know you guys mentioned something that you were working on react-navigation in on of the react-native monthly meetings are you guys still going to continue that work ?

Regards
Andrei

**Comment by zrumenjak** [comment]
We investigated several different options for navigation, but our conclusion was that none of them are stable enough to switch to at the moment. We have built a lot of apps and extensions, so switching to a different navigation solution would require updating all of those. We decided to wait until the native navigation solutions (from wix, and airbnb) come out, and revisit this topic at that time.

For now, you should be able to use react navigation with shoutem/ui without problems. You can even connect react navigation components to your theme, if you plan to build themes, and want to be able to customize the styling of those components through your themes.

**Comment by natterstefan** [comment]
@zrumenjak 

> For now, you should be able to use react navigation with shoutem/ui without problems.

I am not sure if this is related (https://gph.is/VwPfns), but I had to upgrade these packages to make shoutem/ui and react-native-navigation (wix) work

```
    "react-native-linear-gradient": "2.3.0", // << update this
    "react-native-navigation": "1.1.262", // << update this
    "react-native-photo-view": "1.5.2",
    "react-native-vector-icons": "4.4.2" // << update this
```

Otherwhise I got an error like this one: https://github.com/react-native-community/react-native-linear-gradient/issues/202.
