### ISSUE TITLE
lineHeight for title, heading, etc... should be set in theme variables

### ISSUE THREAD

**Issue by JulianKingman** [shoutem/ui#316]
I was trying to figure out why shoutem wasn't respecting my theme variables for title, etc... It seems that since fontSize is set in text theme variables, lineHeight should as well, whereas right now it's set in the theme definition (example: https://github.com/shoutem/ui/blob/3bc085622430d9929e3d97dddad3446cb8b8f603/theme.js#L349). Shall I submit a PR?

**Comment by SoHotSoup** [comment]
Hey @JulianKingman,

please submit that PR, I would do it by changing the order of property merging:
```
'shoutem.ui.Title': {
    [INCLUDE]: ['text'],
    lineHeight: 25,
    ...variables.title,
  },
```

The Idea is that if `variables.title` doesn't have `lineHeight` it still would have it defined. This is important for users who doesn't have lineHeight in its variables.

**Comment by JulianKingman** [comment]
PR Made: https://github.com/shoutem/ui/pull/317
