### ISSUE TITLE
Can we get Shoutem Basic Boilerplate ?

### ISSUE THREAD

**Issue by deadcoder0904** [shoutem/ui#319]
I've tried installing 20 times until now but it just doesn't work. I've checked all the issues tried & tested things like bumping up version number of `react-native-linear-gradient` & all the other issues but it doesn't work.

So I think a starter app would help beginners just to clone Basic Shoutem Example App & type just `yarn` & get started using Shoutem.

& I think maintainers of this repo should make it as they are using it in production. So plz make it easy to start with. As this is the best looking UI Kit for React Native IMO

**Comment by cyrsis** [comment]
+ 1

**Comment by Unforgiven-wanda** [comment]
Can't upvote this enough

**Comment by FFFra** [comment]
same here

**Comment by Vladimir-Vdovic** [comment]
Hey guys,

With the release of 0.22.0, we've updated the example apps, there's minor fixes that'll be included in 0.22.1 soon. 

If you head over to the [repo](https://github.com/shoutem/ui) and clone it, the example apps should both work after being installed(`npm install`) and in the case of the Restaurants app, linked (`react-native link`).

Closing this issue as resolved.
