### ISSUE TITLE
Drop down menu performance issue on ios

### ISSUE THREAD

**Issue by vpanjganj** [shoutem/ui#32]
Drop down menus in the example take a long time to render the menu items. Transition is not smooth at all.

**Comment by SoHotSoup** [comment]
Could you write us more details, about the device, os, and which particular example? That would be of much help to us. Thank you in advance!

**Comment by vpanjganj** [comment]
Oh sorry about that. iphone 6 , ios 10.0.1 . The problem is within the drop down (all of them) I noticed it in the 'Examples component' after following your instructions in 'readme'.

**Comment by SoHotSoup** [comment]
Thank you! We are going to profile it...

**Comment by pauliusuza** [comment]
I can see poor performing drop down animation on Android as well, so this might not be iOS specific. One Plus 3 running on 6.0.1

Fade out (close dropdown) animation is less problematic. Can it be that animation is affected by mounting components?

**Comment by acornejo** [comment]
I also see performance issues in dropdown for android, running on nexus 6p nougat.

Close button doesn't always work and requires two clicks.

**Comment by zrumenjak** [comment]
This is a very old issue, we have made a lot of performance improvements in the meantime, and the DropDown should now work much better.
