### ISSUE TITLE
UI toolkit broken due to change in proptypes package

### ISSUE THREAD

**Issue by chris-rowe** [shoutem/ui#325]
The UI toolkit is not currently working due to the proptypes package being removed from the core react project.
The npm package prop-types is a new dependency.

`import { Proptypes } from 'react';`
needs to be changed to:
`import Proptypes from 'prop-types';`

**Comment by Vladimir-Vdovic** [comment]
This has been resolved with [version 0.22.0](https://www.npmjs.com/package/@shoutem/ui).
