### ISSUE TITLE
React.createClass is deprecated and causing build errors

### ISSUE THREAD

**Issue by chris-rowe** [shoutem/ui#327]
There are files in the shoutem ui kit that are still leveraging React.createClass which is now deprecated. This will cause issues with using the newest version of RN and React. There is a code mod tool that will convert those files into the proper format at: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

This page also shows how the codemod tool can be used to convert createClass files.

**Comment by Vladimir-Vdovic** [comment]
This was the Lightbox component we've forked. We've updated the fork and this is no longer an issue as of [version 0.22.0](https://www.npmjs.com/package/@shoutem/ui).
