### ISSUE TITLE
npm ERR! peer dep missing

### ISSUE THREAD

**Issue by JoshYuJump** [shoutem/ui#330]
I got the error when I run `npm list` in my project root folder.

> npm ERR! peer dep missing: react@^15.0.0, required by @shoutem/ui@0.21.3
> npm ERR! peer dep missing: react@^15.4.2, required by react-test-renderer@15.4.2
> npm ERR! peer dep missing: react@^15.0.0, required by @shoutem/animation@0.11.0
> npm ERR! peer dep missing: react@^15.1.0, required by @shoutem/theme@0.10.0

React Native Version：
"react": "^16.0.0-alpha.12",
"react-native": "^0.45.1",

**Comment by Vladimir-Vdovic** [comment]
This is because of the `-alpha.12`, semver can't recognize that as a higher version than 15.4.2, so it issues an error. You can safely ignore those messages.
