### ISSUE TITLE
android build error when using RN 0.49.5

### ISSUE THREAD

**Issue by Joel-Raju** [shoutem/ui#333]
When using RN 0.49.5 the android build fails. 

***package.json***

    {
      "name": "MyProject",
      "version": "0.0.1",
      "private": true,
      "scripts": {
        "start": "node node_modules/react-native/local-cli/cli.js start",
        "test": "jest"
      },
      "dependencies": {
        "@shoutem/ui": "^0.21.3",
        "react": "16.0.0-beta.5",
        "react-native": "0.49.5",
        "react-redux": "^5.0.6",
        "redux": "^3.7.2",
        "redux-thunk": "^2.2.0"
      },
      "devDependencies": {
        "babel-eslint": "^8.0.1",
        "babel-jest": "21.2.0",
        "babel-preset-react-native": "4.0.0",
        "eslint": "^4.10.0",
        "eslint-config-airbnb": "^16.1.0",
        "eslint-plugin-import": "^2.8.0",
        "eslint-plugin-jsx-a11y": "^6.0.2",
        "eslint-plugin-react": "^7.4.0",
        "jest": "21.2.1",
        "react-test-renderer": "16.0.0-beta.5"
      },
      "jest": {
        "preset": "react-native"
      }
    }

***stack dump***

    :app:preBuild UP-TO-DATE
    :app:preDebugBuild UP-TO-DATE
    :app:checkDebugManifest
    :app:preReleaseBuild UP-TO-DATE
    :app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
    :app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
    :app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DA                                                                                                                                  TE
    :app:prepareComFacebookFrescoDrawee130Library UP-TO-DATE
    :app:prepareComFacebookFrescoFbcore130Library UP-TO-DATE
    :app:prepareComFacebookFrescoFresco130Library UP-TO-DATE
    :app:prepareComFacebookFrescoImagepipeline130Library UP-TO-DATE
    :app:prepareComFacebookFrescoImagepipelineBase130Library UP-TO-DATE
    :app:prepareComFacebookFrescoImagepipelineOkhttp3130Library UP-TO-DATE
    :app:prepareComFacebookReactReactNative0495Library UP-TO-DATE
    :app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
    :app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
    :app:prepareDebugDependencies
    :app:compileDebugAidl UP-TO-DATE
    :app:compileDebugRenderscript UP-TO-DATE
    :app:generateDebugBuildConfig UP-TO-DATE
    :app:mergeDebugShaders UP-TO-DATE
    :app:compileDebugShaders UP-TO-DATE
    :app:generateDebugAssets UP-TO-DATE
    :app:mergeDebugAssets UP-TO-DATE
    :app:generateDebugResValues UP-TO-DATE
    :app:generateDebugResources UP-TO-DATE
    :app:mergeDebugResources UP-TO-DATE
    :app:bundleDebugJsAndAssets SKIPPED
    :app:processDebugManifest UP-TO-DATE
    :app:processDebugResources UP-TO-DATE
    :app:generateDebugSources UP-TO-DATE
    :app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
    :app:compileDebugJavaWithJavac
    :app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed,                                                                                                                                   no previous execution, etc.).
    D:\projects\design-talks\android\app\src\main\java\com\designtalks\MainApplicati                                                                                                                                  on.java:6: error: package com.reactnative.photoview does not exist
    import com.reactnative.photoview.PhotoViewPackage;
                                    ^
    D:\projects\design-talks\android\app\src\main\java\com\designtalks\MainApplicati                                                                                                                                  on.java:7: error: package cl.json does not exist
    import cl.json.RNSharePackage;
                  ^
    D:\projects\design-talks\android\app\src\main\java\com\designtalks\MainApplicati                                                                                                                                  on.java:8: error: package com.BV.LinearGradient does not exist
    import com.BV.LinearGradient.LinearGradientPackage;
                                ^
    D:\projects\design-talks\android\app\src\main\java\com\designtalks\MainApplicati                                                                                                                                  on.java:9: error: package com.oblador.vectoricons does not exist
    import com.oblador.vectoricons.VectorIconsPackage;
                                  ^
    D:\projects\design-talks\android\app\src\main\java\com\designtalks\MainApplicati                                                                                                                                  on.java:30: error: cannot find symbol
                new PhotoViewPackage(),
                    ^
      symbol: class PhotoViewPackage
    D:\projects\design-talks\android\app\src\main\java\com\designtalks\MainApplicati                                                                                                                                  on.java:31: error: cannot find symbol
                new RNSharePackage(),
                    ^
      symbol: class RNSharePackage
    D:\projects\design-talks\android\app\src\main\java\com\designtalks\MainApplicati                                                                                                                                  on.java:32: error: cannot find symbol
                new LinearGradientPackage(),
                    ^
      symbol: class LinearGradientPackage
    D:\projects\design-talks\android\app\src\main\java\com\designtalks\MainApplicati                                                                                                                                  on.java:33: error: cannot find symbol
                new VectorIconsPackage()
                    ^
      symbol: class VectorIconsPackage
    8 errors
    :app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

**Comment by Vladimir-Vdovic** [comment]
Hi @Joel-Raju,

We've recently released [version 0.22.0](https://www.npmjs.com/package/@shoutem/ui) which includes fixes for dependencies that were causing Android builds to fail, as well as compatibility for React Native 0.50.3 and other fixes and improvements.

Closing issue as it's resolved.
