### ISSUE TITLE
ui doesn't work well on Android?

### ISSUE THREAD

**Issue by 1c7** [shoutem/ui#338]
# I follow these step
![image](https://user-images.githubusercontent.com/1804755/33935669-bfa8924a-e037-11e7-8d0a-f04489d7df11.png)

## using React Native 0.51
![image](https://user-images.githubusercontent.com/1804755/33935690-d1ba7e8a-e037-11e7-8b06-19db39b0e7e1.png)

## Result I got
![image](https://user-images.githubusercontent.com/1804755/33935703-df626552-e037-11e7-8fa0-01e491549faa.png)

![image](https://user-images.githubusercontent.com/1804755/33935722-ed50881a-e037-11e7-8c83-7c657964f883.png)

![image](https://user-images.githubusercontent.com/1804755/33935736-faa9c77e-e037-11e7-9339-8e6ed16eb41e.png)

![image](https://user-images.githubusercontent.com/1804755/33935771-10149a94-e038-11e7-9766-b5f309a0ac9b.png)

## Question
is this my problem? am I doing anything wrong?

how to fix this?

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/33935864-583fd022-e038-11e7-9f9d-6b8cc9b6b434.png)

**Comment by 1c7** [comment]
work well on iOS
![image](https://user-images.githubusercontent.com/1804755/33935931-a0742802-e038-11e7-9884-605d18c5a54f.png)
![image](https://user-images.githubusercontent.com/1804755/33935937-a82e0464-e038-11e7-97e9-38d37e4ac28b.png)
![image](https://user-images.githubusercontent.com/1804755/33935949-b557472c-e038-11e7-9894-818a5dadff97.png)
![image](https://user-images.githubusercontent.com/1804755/33935967-bfc1f568-e038-11e7-8e06-e47577a5d297.png)

**Comment by 1c7** [comment]
## Wait
## Seem like I forgot "react-native link"
now it work
![image](https://user-images.githubusercontent.com/1804755/33936033-fd9c3722-e038-11e7-8271-ac34dce7b6f9.png)

**Comment by 1c7** [comment]
conclusion: problem fixed by running "react-native link"

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/33936115-5a2787a8-e039-11e7-8b79-b9d5aacb1044.png)

**Comment by Vladimir-Vdovic** [comment]
It's definitely the `react-native link`, because the icons are loaded as a font, so they need to be linked. Glad you figured it out!

**Comment by 1c7** [comment]
@Vladimir-Vdovic Thanks!

**Comment by 1c7** [comment]
shoutem/ui is very useful, Thanks for open source it and maintain it! 
@Vladimir-Vdovic 

by the way,
right now I am looking for way to build Tab at bottom, "TabNavigator" from 'react-navigation' work well on iOS, but not Android (the look is different)

I want both iOS and Android look like the left(Icon and Text)
![image](https://user-images.githubusercontent.com/1804755/33947288-f6f8b104-e05e-11e7-82a2-91c9509c2d4b.png)

any thought? I am beginner on RN, still learning
 :D

**Comment by Vladimir-Vdovic** [comment]
This is not related to the Shoutem UI toolkit, you're much better off asking this on the [react-navigation](https://github.com/react-community/react-navigation) repository.

But I believe this is intended, to match native implementations of tab bar navigation. You can see the same thing on example images like [this](https://cdn-images-1.medium.com/max/1600/1*VtueqWFHiOkTa-oREtMLHA.png) one.

**Comment by 1c7** [comment]
@Vladimir-Vdovic got it, Thanks!
