### ISSUE TITLE
npm install --save @shoutem/ui throwing errors 

### ISSUE THREAD

**Issue by arudrakalyan** [shoutem/ui#350]
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git checkout fbce4b9e478f808634a98dac48901ec6ed4ee9fd
npm ERR! fatal: reference is not a tree: fbce4b9e478f808634a98dac48901ec6ed4ee9fd
npm ERR!

**Comment by alanbrice** [comment]
I have the same problem

**Comment by Bcamargoz** [comment]
I have the same problem, some solution?

**Comment by Bcamargoz** [comment]
Based on the example project I can install the library in a previous version "0.22.0", manually adding to the package.json file the line "@shoutem/ui": "0.22.0" this should only be temporary, let's wait official response

**Comment by mtimsit** [comment]
Got the same problem with a new project on expo 24

**Comment by mtimsit** [comment]
@Bcamargoz:  it didn't work for me by adding manually the line in the package.json. npm install crashed too

**Comment by mtimsit** [comment]
The problem comes from specific version 0.22.3 and 0.22.2.
Find a workaround by installing a correct version: `npm install --save @shoutem/ui@0.22.1`

**Comment by Vladimir-Vdovic** [comment]
Hey guys, this is an issue stemming from a faulty dependency referencing a commit. Will resolve immediately with version 0.22.4.

There are no noteworthy changes between 0.22.1 and 0.22.3 so you guys are safe to use it.

I'll close this issue after 0.22.4 is released with the dependency fix, I'll also comment so you guys are notified.

**Comment by Vladimir-Vdovic** [comment]
Version 0.22.4 is now available, this issue should be resolved. Prompt for reopen if the issue continues.

**Comment by mtimsit** [comment]
Thanks @Vladimir-Vdovic
