### ISSUE TITLE
Dropdownmenu

### ISSUE THREAD

**Issue by asrma7** [shoutem/ui#354]
Is it possible to add icon in menulist (options) of dropdownmenu?
for example When I open Dropdownmenu, It should appear as home icon + Home, About Icon + About us... and so on

**Comment by banovotz** [comment]
__________________________________
Please type your reply at the top of the email...

------------------------------------------------------


Shoutem | Jan 09, 2018 10:47AM UTC   

Hello shoutem/ui,
thank you for submitting your request. We have received your request and are working on responding to you as soon as possible. If you have any additional information to add to this case, please reply to this email.


Thanks in advance for your patience and support.


------------------------------------------------------

For your reference this is Case #: 188323

------------------------------------------------------


Support powered by Assistly (http://www.assistly.com/)

[[1b109e31610c282056a23d15043d6b259feee22f-1119048019]]
