### ISSUE TITLE
NavigationBar left and right component have no padding at the sides

### ISSUE THREAD

**Issue by imolorhe** [shoutem/ui#358]
I just started using shoutem and have been facing some issues with using it. The examples on the site seem to be outdated. The Image component for example doesn't allow children (according to the error message I kept getting) but the example still adds children to the image component.
The NavigationBar component also needs the `inline` style name to be added for it to work as expected. I found out by going through the closed issues. Now I have this new issue and I haven't yet seen any issues on it. There is no padding to the left and right of the navigation bar content. I've searched through the component documentation on the site over and over again with no clues as to why this is the way it is 😔. The examples show the component with paddings to the sides. Do I need to add another style name to the component?

```
<Screen>
        <NavigationBar
          styleName='inline'
          leftComponent={<Icon name="sidebar" />}
          rightComponent={<Icon name="search" />}
        />

        <ListView
          data={groupedData}
          renderRow={this.renderRow}
        />
      </Screen>
```

<img width="424" alt="screen shot 2018-01-18 at 1 40 54 am" src="https://user-images.githubusercontent.com/4608143/35074947-bd00c97a-fbf0-11e7-96a5-e22e41f58b48.png">

**Comment by JelaniThompson** [comment]
Bump.

**Comment by imolorhe** [comment]
@JelaniThompson Bump?

**Comment by TAHERx** [comment]
i have this issue too
but you can fix it by using `style={{paddingLeft: 15}}` and `style={{paddingRight: 15}}`

```
<Screen>
        <NavigationBar
          styleName='inline'
          leftComponent={<Icon style={{paddingLeft: 15}} name="sidebar" />}
          rightComponent={<Icon style={{paddingRight: 15}} name="search" />}
        />

        <ListView
          data={groupedData}
          renderRow={this.renderRow}
        />
      </Screen>
```

**Comment by Vladimir-Vdovic** [comment]
This has been resolved with the latest release of the UI toolkit.
