### ISSUE TITLE
Restaurant Example and Shoutem UI Framework are broken

### ISSUE THREAD

**Issue by chenbekor** [shoutem/ui#363]
how to reproduce:

1. start from scratch - git clone the ui project
2. go to folder examples
3. go to folder RestaurantsApp
4. npm install
5. react-native link
6. react-native run-ios

You will see an error: ReferenceError: Can't find variable: ImageBackground

Can you please fix that urgently?

Please note that this error is not only influencing the example project. the entire shoutem ui framework is totally broken since commit 1952307 (about 14 days ago)

Personally I only managed to use version 0.21.1 - all recent versions are broken...

**Comment by archywilhes** [comment]
@chenbekor no this error is only affecting the demo and not the entire shoutem ui library. don't spread rumours like this when you don't even bother to understand what exactly is going on. The demo works fine with you just do a global `%s/ImageBackground/Image/g` as demonstrated in a recent pull request.

**Comment by jeffreywstevens** [comment]
Can you explain "You just need to do a global %s/ImageBackground/Image/g" to someone new to this framework?  I admit I do use examples as sort of a unit test until I get more familiar with the technology.

**Comment by joshcrews** [comment]
@jeffreywstevens I think I found what to do.
Globally replace ImageBackground with Image
You can see what someone did in this pull request: https://github.com/shoutem/ui/pull/360

**Comment by jeffreywstevens** [comment]
I did that.  
However I then received an "Image component can't contain children" error.  
I fixed it by making the children siblings  Not sure if the alignment is like the original but it runs and I can move on.

**Comment by zargold** [comment]
I was able to get it working with a tiny bit of work. I think it basically works. I don't know exactly what I did but I did start with create-react-app then copy-pasta'd the same Restaurant project into App.js

**Comment by Vladimir-Vdovic** [comment]
Thanks to @zargold's pull request, the Restaurants example is now up to date again.

Closing this issue as it's now resolved.
