### ISSUE TITLE
Just to be sure: it's free?

### ISSUE THREAD

**Issue by zargold** [shoutem/ui#368]
I can use these components much like I would use a "bootstrap" type framework in any personal and commercial project. Because it is BSD?

But then you have a commercial project as well right? And that would give a user access to the same tools without having to code and instead using a CMS?

**Comment by dodsky** [comment]
Yes. The UI toolkit is free to use library. 
We have a paid service where you can create a React Native app. It's free to develop extensions for Shoutem apps too. Backend services (user auth, CMS, analytics, push notifications, automatic publishing) are paid (https://new.shoutem.com/pricing/).
