### ISSUE TITLE
Enable Use Of Style Property

### ISSUE THREAD

**Issue by Pczek** [shoutem/ui#375]
IMHO it's a pain in the ass that I can not adapt the components style by passing a style prop. For example simply changing the color of one of the Typography components is impossible.

```jsx
<Heading style={{color:'green'}}>Random Heading</Heading>
```

 I can understand that you want to preserve a consistent style and don't want your components to be misused to create an ugly app but the provided 'styleNames' are quite limited and I stumbled across a couple of situations I wanted to slightly adapt a component or create a new one from existing ones.

Using a the passed style prop can be used like this in order to adapt the shoutem ui style.

```jsx
const Heading = ({value, style}) => (
    <Text style={{...shoutemUIHeadingStyle, ...style}}>
        {value}
    </Text>
)
```

Nevertheless, most beautiful react-native ui kit yet, keep up the good work. 👍

**Comment by Vladimir-Vdovic** [comment]
You can always extend the `styleName`s by adding your own or overwriting any existing ones. Check out this [SO answer](https://stackoverflow.com/questions/46054523/shoutem-change-default-fontfamily-not-work/46058338#46058338).

Thank you for the kind words.
