### ISSUE TITLE
Unrecognized font family 'Rubik-Regular'

### ISSUE THREAD

**Issue by pavinthan** [shoutem/ui#382]
```
react-native-cli: 2.0.1
react-native: 0.52.0

"@shoutem/ui": "^0.23.4",
```

I already run react-native link but still, I get `Unrecognized font family 'Rubik-Regular'`

**Comment by kraisorns** [comment]
I got into this issue too but just restart server and it should work fine.

**Comment by devomacdee** [comment]
This was broken for me too, restarting the server did nothing. Also none of the previous fixes worked. Just a good reason not to use this lib.

**Comment by alainpatrick** [comment]
You might need to load the fonts.
Check this example out: 
https://github.com/shoutem/ui/blob/develop/examples/create-react-native-app/App.js

Please let me know if it solves your problem.

**Comment by alainpatrick** [comment]
- one option is to create your app using expo, then detach it: https://docs.expo.io/versions/latest/expokit/detach
- the other could be to use a library like this one: 
https://github.com/eVisit/react-native-dynamic-fonts
I haven't used the later, so experiment with it
- last option would be to go through this tutorial and adapt it: 
https://medium.com/react-native-training/react-native-custom-fonts-ccc9aacf9e5e

Hope this helps.

**Comment by motogod** [comment]
I restart server is no working but when i try to type command react-native link and run ios then its working.

**Comment by SilencerWeb** [comment]
omg, srsly? still not working? the first issue was opened almost 2 years ago, lol https://github.com/shoutem/ui/issues/95

**Comment by Salil999** [comment]
This is still an issue. I'm saddened as the UI components in this library really look pretty.

**Comment by pavinthan** [comment]
Clean build folder and node_modules then link ( `react-native link` ) dependencies fixed the issue.

Thanks for your support guys 🙏
