### ISSUE TITLE
Should update ListView to Flatlist or SectionList

### ISSUE THREAD

**Issue by andynguy3n** [shoutem/ui#409]
According to this one: https://facebook.github.io/react-native/docs/listview.

> DEPRECATED - use one of the new list components, such as FlatList or SectionList for bounded memory use, fewer bugs, better performance, an easier to use API, and more features. Check out this [blog post](https://facebook.github.io/react-native/blog/2017/03/13/better-list-views.html) for more details.

I saw we are using ListView for many components, such as ListView, Dropdown Menu...

We must update ListView from our framework to Flatlist or SectionList. Do we have any plans to update it?

Thanks in advance.

**Comment by jack828** [comment]
This should be addressed - as of RN 0.60.4 ListView has been removed.

**Comment by Vladimir-Vdovic** [comment]
Hey guys,

A new UI toolkit will be coming out shortly (most likely 1.0.0) that has a component called ListView, but it runs on  FlatList and SectionList under the hood, also giving you an easy way to render a featured item, that being the first item in the data you pass to it.

We'll be updating the docs for our ListView component as we release this to cover the newly expanded API with `renderFeaturedItem` as well as any other details that may change in how to pass `renderRow` and `data` and of course sections and section header renderers.

**Comment by Vladimir-Vdovic** [comment]
We've now release `@shoutem/ui@1.0.0` which should provide compatibility with at least 0.59.10, if not 0.60.x.

[Release 1.0.0](https://github.com/shoutem/ui/releases/tag/v1.0.0)

`ListView` prop changes can be viewed on the `@shoutem/ui` [docs](https://shoutem.github.io/docs/ui-toolkit/components/list-view).
