### ISSUE TITLE
"rnpm" is still being referred to in README

### ISSUE THREAD

**Issue by banovotz** [shoutem/ui#41]
The rnpm command  is still referred in the README file Shouldn't we used the "react-native link"?

See
https://github.com/shoutem/ui/commit/1fdf9d64f2861e51a2bb944fc52993e22ad25493

**Comment by banovotz** [comment]
https://shoutem.desk.com/agent/case/135269

**Comment by SoHotSoup** [comment]
referred commit is still unpublished to npm, we are going to release it today.
