### ISSUE TITLE
Invariant Violation: requireNativeComponent: "BVLinearGradient" was not found in the UIManager.

### ISSUE THREAD

**Issue by visagegod** [shoutem/ui#413]
Hi, attempting to use LinearGradient as so:

`import {LinearGradient} from '@shoutem/ui'`

`...
render() { return (
       <LinearGradient colors={['#4c669f', '#3b5998', '#192f6a']} style={{flex: 1}}></LinearGradient>
)}
...`

This is the error I get at `react-native run-android`:

`Invariant Violation: requireNativeComponent: "BVLinearGradient" was not found in the UIManager.`

I have tried npm uninstall react-native-linear-gradient & npm install react-native-linear-gradient & react-native link etc. with no success'?

Can anyone provide me with some assistance?

Thanks!

**Comment by mrtomhoward** [comment]
@visagegod I just hit this error too, after upgrading my version of RN and of `react-native-linear-gradient`.
It seems the **link** command isn't working properly, and you need to install it manually - particularly the **Link Binary With Libraries** part.

**Comment by lygrn** [comment]
My god! I have the same question.

**Comment by Miko2x** [comment]
anyone, please solve this error :(

**Comment by KouSyurei** [comment]
Hey, guys, have you solved this problem, and I have. The 'BVLinearGradient' was lost at reactNative

**Comment by hexrcs** [comment]
Hitting this issue too. Which RN version are you guys on? I'm on 0.57.4.

**Comment by indiorlei** [comment]
271/5000
Just add "BVLinearGradient" in xcode libs.
You can drag the BVLinearGradient.xcodeproj file from the node_modules / react-native-linear-gradient for your project libraries in xcode and then add the lib in General> Linked Frameworks and Libraries.

<img width="1440" alt="captura de tela 2019-01-16 as 08 37 13" src="https://user-images.githubusercontent.com/5550084/51243717-6009e600-196a-11e9-9827-971acdcebd4f.png">

**Comment by visagegod** [comment]
Closing issue because noone should be using shoutem/ui, very out of date library and looks like no dev activity

**Comment by TranVanThaiSon** [comment]
> 271/5000
> Just add "BVLinearGradient" in xcode libs.
> You can drag the BVLinearGradient.xcodeproj file from the node_modules / react-native-linear-gradient for your project libraries in xcode and then add the lib in General> Linked Frameworks and Libraries.
> 
> <img alt="captura de tela 2019-01-16 as 08 37 13" width="1440" src="https://user-images.githubusercontent.com/5550084/51243717-6009e600-196a-11e9-9827-971acdcebd4f.png">
 it work for me. Thanks

**Comment by rafaelbpa** [comment]
All I had to do is run the command "react-native run-ios" again to fix the issue.

**Comment by tanvirbhatti** [comment]
after all that just try to run "react-native run-android" again
