### ISSUE TITLE
Lots of dependencies errors with latest React Native 0.59.8

### ISSUE THREAD

**Issue by actooalizame** [shoutem/ui#433]
I'm running on a **fresh install of React Native 0.59.8**. Windows 10 platform.

**Only package installed on my project is Shoutem UI**. 

I'm getting this strange, long, dependencies error, which I'm not able to solve at all. 
Note: **This doesn't happen with React Native 0.57, only with latest 0.59 version**.
I'm attaching captures since the console output is too long to copy-paste without being annoying.

**Anyone else having this issue?** Please help me resolve this.
I'm a little bit worried since React Native 0.59 is the first to support 64bit, as required by Google Play, starting August 1st .

![cap-bug-shoutemui-1](https://user-images.githubusercontent.com/11241403/58143165-d3bd4780-7c17-11e9-88ad-3fe4b1b4cb70.jpg)
![cap-bug-shoutemui-2](https://user-images.githubusercontent.com/11241403/58143184-e2a3fa00-7c17-11e9-8af2-8af441d2e5f4.jpg)
![cap-bug-shoutemui-3](https://user-images.githubusercontent.com/11241403/58143194-ec2d6200-7c17-11e9-8cbc-a53ffbbc7f2a.jpg)
![cap-bug-shoutemui-4](https://user-images.githubusercontent.com/11241403/58143198-f0f21600-7c17-11e9-8d2f-d3836ffce486.jpg)

The output goes on... But I only included four screencaps for brevity.

Thanks in advance.

**Comment by DrPoppyseed** [comment]
I'm having many issues as well, mainly 'unrecognized font' errors and many more that seem to occur after trying to use shoutem.

**Comment by actooalizame** [comment]
Managed to fix it by
```

npm install --save react-native-vector-icons
react-native link react-native-vector-icons
npm install --save react-native-photo-view
react-native link react-native-photo-view
```
Then it threw the error fixed here: https://github.com/react-native-community/react-native-linear-gradient/issues/356#issuecomment-460044459
