### ISSUE TITLE
Does not work with Expo expo 33.0.0, which is based on react native 0.59

### ISSUE THREAD

**Issue by fwcontact** [shoutem/ui#438]
@shoutem/ui version 0.23.20

Unable to resolve module `react-native/Libraries/StyleSheet/ColorPropType.js` from `/Users/X/Work/GIT/projectX/node_modules/@shoutem/ui/node_modules/react-native-linear-gradient/index.ios.js`: Module `react-native/Libraries/StyleSheet/ColorPropType.js` does not exist in the Haste module map

**Comment by jack828** [comment]
Hi, I had the same issue, and as per https://github.com/shoutem/ui/issues/439#issuecomment-506679184, this helped me https://github.com/shoutem/ui/issues/424#issuecomment-4714643440
