### ISSUE TITLE
Text crop when placing in Tile with custom fontFamily

### ISSUE THREAD

**Issue by arshavinho** [shoutem/ui#45]
I'm trying to use another fontFamily with this code:
```javascript
<ScrollView style={styles.scrollview} {...driver.scrollViewProps}>
          <HeroHeader driver={driver}>
            <Image
              style={styles.cover} source={{uri: this.props.image}}
            >
              <Tile>
                <Parallax driver={driver} scrollSpeed={1.2} header>
                  <FadeIn inputRange={[-20, 0]} driver={driver}>
                    <FadeOut inputRange={[100, 150]} driver={driver}>
                      <Title style={styles.titleStyle}>{this.props.title}</Title>
                    </FadeOut>
                  </FadeIn>
                </Parallax>
              </Tile>
            </Image>
          </HeroHeader>
        </ScrollView>
```
...

```javascript
const styles = {
  titleStyle: {
    textAlign: 'center',
    fontFamily: 'AmericanCaptain',
    fontSize: 40,
    height: 100,
    color: 'white'
  }
}
```
If the fontSize is greater than 25 the text is crop like this:

![text-crop](https://cloud.githubusercontent.com/assets/1016441/18846328/a405428c-8425-11e6-907f-416482e7a7e0.png)

Do you have any idea how can i avoid that?

Thanks!

**Comment by SoHotSoup** [comment]
Did you try to change `lineHeight`? Also, if that doesn't help you, please try to remove animations, so it would be easier for us to find a cause...

Thank you!

**Comment by arshavinho** [comment]
lineHeight works great, thank you!

**Comment by SoHotSoup** [comment]
Also, you can get the same animation by using ScrollView from @shoutem/ui

```javascript
import {
  Image,
  ScrollView,
  Title,
  Tile,
} from '@shoutem/ui';

...

render() {
  return (
    <ScrollView>
      <Image animationName="hero">
        <Tile animationName="hero">
          <Title>My Title</Title>
        </Tile>
      </Image>
    </ScrollView>
  );
}
```

Our components are decorated by Higher order component `connectAnimation` from `@shoutem/animation` which allows definition of reusable animations in style. Check style for `Image` and `Tile` in theme.js they have defined this `hero` animation which you are trying to achieve... 😄

**Comment by arshavinho** [comment]
oh i see i will try ! thanks,
i'm trying to add a View with a background: 'black' and an animated opactity to cover the "hero" image when i scroll down to have my Text more visible to avoid this:
![screen shot 2016-09-27 at 18 30 30](https://cloud.githubusercontent.com/assets/1016441/18882695/98cd2694-84e0-11e6-8b60-2f8db223ae4d.png)
 i'm probably sur you have an idea 💃

**Comment by arshavinho** [comment]
Using ScrollView from @shoutem/ui it's far more easy 👍

**Comment by SoHotSoup** [comment]
Could you paste code snippet here? It should work just by putting View as sibling component of Image...

**Comment by arshavinho** [comment]
```javascript
render() {

    return(
      <View style={styles.container}>
        <ScrollView style={styles.scrollview}>
          <Image
            animationName="hero"
            style={styles.cover} source={{uri: this.props.image}}
          >
            <Tile animationName="hero">
              <Title style={styles.titleStyle}>{this.props.title}</Title>
            </Tile>
          </Image>
          <Text style={styles.subtitleStyle}>{this.props.subtitle}</Text>
        </ScrollView>
      </View>
    )
  }
```

I'm trying to have a view with the dimension of the Image, with backgroundColor black with an opacity animate with the scroll

**Comment by SoHotSoup** [comment]
Just wrapText with this View. View should be inside of ScrollView. :)

**Comment by arshavinho** [comment]
Sorry i didn't succeed ⭕ 
Do you have an example?

**Comment by SoHotSoup** [comment]
```javascript
render() {

    return(
        <ScrollView style={styles.scrollview}>
          <Image
            animationName="hero"
            style={styles.cover} source={{uri: this.props.image}}
          >
            <Tile animationName="hero">
              <Title style={styles.titleStyle}>{this.props.title}</Title>
            </Tile>
          </Image>
          <View style={styles.container}>
             <Text style={styles.subtitleStyle}>{this.props.subtitle}</Text>
           </View>
        </ScrollView>
    )
  }
```

**Comment by arshavinho** [comment]
Sorry for the delay,
i tried but it's just a black opaque view behind the subtitle, 
what i try to achieve it's to have my description ( "Sam Wilson ... ) on the bottom like that :
![marvel1](https://cloud.githubusercontent.com/assets/1016441/18965630/4b44ec64-867e-11e6-94ba-f91e19d0033b.png)
 
But when i scroll the ScrollView, the opacity on the Image will increase so that my description will be more visible, instead of right now i have my description on a transparent background 

![marvel2](https://cloud.githubusercontent.com/assets/1016441/18965814/fea32410-867e-11e6-94fc-f4e7e1ad6a77.png)

Sorry if I didn't explain myself properly the first time
