### ISSUE TITLE
Cannot install @shoutem/ui

### ISSUE THREAD

**Issue by chaimaM** [shoutem/ui#464]
Hello guys I am facing issues while  installing @shoutem/ui with npm.
Here is the  error that I get when I try  ` npm i @shoutem/ui@1.0.1`

`npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/shoutem/react-native-lightbox.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
`

**Comment by Randore** [comment]
Why this is close, I still see the error message
