### ISSUE TITLE
Images not displaying in the simulator

### ISSUE THREAD

**Issue by pjb3** [shoutem/ui#47]
When I render an image, copying and pasting the same code from the examples, such as this one:

```jsx
<Image
  styleName="featured"
  source={{ uri: 'http://shoutem.github.io/img/ui-toolkit/examples/image-4.png' }}
>
  <Tile>
    <Title styleName="md-gutter-bottom">MIKE PATTON TEAMING WITH JOHN KAADA FOR COLLAB ALBUM BACTERIA CULT</Title>
    <Caption>Sophia Jackson        21 hours ago</Caption>
  </Tile>
</Image>
```

It looks like this:

![screen shot 2016-09-27 at 11 25 02 pm](https://cloud.githubusercontent.com/assets/726/18899836/de595d9e-8509-11e6-8b19-f710edf01946.png)

And if I stop the app, open Safari in the simulator, copy and paste the same image URL into the address bar, the image shows up fine. So it just doesn't display in the app.

**Comment by ikalafat** [comment]
Hi @pjb3,

Try to replace `http://` in url with `https://`, like below,

```
<Image
  styleName="featured"
  source={{ uri: 'https://shoutem.github.io/img/ui-toolkit/examples/image-4.png' }}
>
  <Tile>
    <Title styleName="md-gutter-bottom">MIKE PATTON TEAMING WITH JOHN KAADA FOR COLLAB ALBUM BACTERIA CULT</Title>
    <Caption>Sophia Jackson        21 hours ago</Caption>
  </Tile>
</Image>
```

that should do the trick.

**Comment by pjb3** [comment]
@ikalafat That did it, thanks for your help!

**Comment by ikalafat** [comment]
Great!
