### ISSUE TITLE
Variety number of rows with GridRow

### ISSUE THREAD

**Issue by infacq** [shoutem/ui#48]
> The main idea behind this approach is to allow developers to have a variable number of columns in each row, for example: the first row can have only 1 column, followed by a number of rows with 2 columns.

How do I set this up

**Comment by ikalafat** [comment]
Hi @infacq,

We're preparing docs update where we will have better example for GridRow usage.

In meantime, you can check this issue, which partially answers your question: #39. 

as @SoHotSoup mentioned in that issue, `groupByRows` method accepts third argument `getColumnSpan`. and you can use it to change cells column span depending on some parameter for that item. 

For example, if you have some item which should be "featured", and span across two (out of two) columns, you can accomplish that like this:

```
    const groupedItems = GridRow.groupByRows(items, 2,
      (item) => (item.featured ? 2 : 1)
    );
```

Please close this issue if my answer is satisfactory.

**Comment by infacq** [comment]
Thanks @ikalafat

**Comment by ikalafat** [comment]
No problem, glad that I could help.

**Comment by infacq** [comment]
BTW can I set another rowRender for the feature one

**Comment by ikalafat** [comment]
You could achieve it like this:
```
renderRow(items) {
    // Featured articles are rendered in full width, across whole row in separate component
    if (items[0].featured) {
      return (
        <MyFeaturedGridCell
          key={items[0].id}
          data={items[0]}
          onPress={this.openDetailsScreen}
        />
      );
    }

  const cardViews = _.map(items, (item) => {

    return (
      <MyGridCell
        key={item.id}
        data={item}
        onPress={this.openDetailsScreen}
      />
    );
  });

  return (
    <GridRow columns={2}>
      {cardViews}
    </GridRow>
  );
}

renderItems(items) {
  // Group the items into rows with 2 columns
  const groupedItems = GridRow.groupByRows(items, 2,
      (item) => (item.featured ? 2 : 1)
    );

  return (
    <ListView
      data={groupedItems}
      renderRow={this.renderRow}
    />
  );
}
```

This approach will allow you to split rendering of `featured` and `non-featured` cells into two different components (`MyFeaturedGridCell` and `MyGridCell`), and avoid having double rederRow method, and it should make code more readable in respect to having two very similar renderRow methods.
