### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by nelsonkam** [shoutem/ui#52]
`rnpm` has been merged to `react-native` core therefore README.md file and subsequent documentation should be updated. [rnpm's github repo](https://github.com/rnpm/rnpm)

> Now, as you may know, RNPM is merged into React Native core. It means that from now on you don't need to install a third-party software to use your favorite linking functionality (just use a react-native cli).

**Comment by MrBr** [comment]
https://github.com/shoutem/ui/issues/41
