### ISSUE TITLE
NavigationBar gets overwritten by other elements

### ISSUE THREAD

**Issue by ekhall** [shoutem/ui#57]
Hi - really enjoying parts of the shoutem library. I'm running into a problem with elements overlapping. I've attached an image - in this, a NavigationBar is being overlapped by the subsequent Tile. The lower border of the NavigationBar is evident at the right border (highlighted).

This does not seem to occur with other elements of the library or with elements I have created myself. Just the NavigationBar. Running the latest released build of shouted/ui, RN 0.34.1

```
<NavigationBar styleName="container"
centerComponent={<Title>TITLE</Title>}
/>
<Image
styleName="featured"
source={{ uri: 'http://shoutem.github.io/img/ui-toolkit/examples/image-11.png' }}
>
<Tile>
<Overlay><Heading>-20%</Heading></Overlay>
<Title styleName="md-gutter-top">COOL BLACK AND WHITE STYLISH WATCHES</Title>
<Subtitle styleName="line-through sm-gutter-top">$280.00</Subtitle>
<Heading>$250.00</Heading>
<Button styleName="md-gutter-top"><Icon name="cart" /><Text>ADD TO BASKET</Text></Button>
</Tile>
</Image>
</View>


)
}


```

<img width="376" alt="screen shot 2016-09-30 at 9 41 43 am" src="https://cloud.githubusercontent.com/assets/1452508/19013394/7a3a1934-879d-11e6-9f82-571057c232e7.png">

**Comment by SoHotSoup** [comment]
Hm, this is probably because NavigationBar is positioned absolute, so it doesn't affect layout. We use it as `navigationBar` component in `Navigator`, so we didn't notice this issue yet. Could you, please, try this:

```javascript
<NavigationBar style={{ container: { zIndex: 1 } }}
centerComponent={<Title>TITLE</Title>}
/>
```

This will make `NavigationBar` rendered at the top of `Image`.

Also, I think we should introduce `styleName="inline"` for `NavigationBar` which would render `NavigationBar` with position `relative`.

**Comment by SoHotSoup** [comment]
cc @ekhall

**Comment by ekhall** [comment]
Thanks man - that works in as much as it positions it higher, although content is still positioned behind it. I believe that's what you're referring to with your last point. Would be super if it was positioned relatively (as I imagine you're pointing out, inline as a styleName doesn't work yet).

Really like these components - thank you and please let me know if I can troubleshoot/help any further.

**Comment by guilhermedecampo** [comment]
Had the same issue here. End up adding a paddingTop on the `Screen` component

```
<Screen
        style={{ paddingTop: 70 }}
      >
        <NavigationBar
          centerComponent={<Title>My Title</Title>}
        />
        <ListView
          data={this.data()}
          renderRow={this.rows}
        />
      </Screen>
```

What do you think in create a `styleName` named `navigation-bar` for Screen component? 
@SoHotSoup

**Comment by SoHotSoup** [comment]
Hey @guilhermedecampo! Sorry for late response, I believe that better option would be to add new `styleName` for `NavigationBar` which would define it as `inline`. Something like this:
```javascript
'.inline': {
  width: window.width,
  position: 'relative',
}
```

That should be enough. Could I ask you to submit PR for it?

**Comment by guilhermedecampo** [comment]
For sure @SoHotSoup

**Comment by SoHotSoup** [comment]
#104
