### ISSUE TITLE
Why I'm getting this error message

### ISSUE THREAD

**Issue by Prathapkarumanchi** [shoutem/ui#588]
Hi, I have installed @shoutem-ui and started with example Hello component but I'm getting the following error message.

Do I need to install any icons like React-icons?

`error: Error: Unable to resolve module ./checkbox-rectangle-off from /Users/../node_modules/@shoutem/ui/components/Icon/assets/index.js: `

<img width="822" alt="Screenshot 2021-04-18 at 3 10 20 PM" src="https://user-images.githubusercontent.com/53927098/115141169-8b537200-a058-11eb-8073-70bdddce3b9d.png">

**Comment by Definitely-Not-Vlad** [comment]
Hi @Prathapkarumanchi, we've resolved this with the newest release, v4.4.2. If you install this version, this error should no longer happen.

Sorry for the inconvenience. If the error persists, feel free to ask for a reopen of this issue.
