### ISSUE TITLE
Can't run RestaurantsApp 

### ISSUE THREAD

**Issue by zh-wowtv** [shoutem/ui#59]
I followed the README of shoutem/ui. But got the following message:

> TransformError: /Users/xxxx/Projects/xxxxx/ui/examples/RestaurantsApp/index.ios.js: Couldn't find preset "react-native" relative to directory "/Users/xxxx/Projects/xxxxx/ui

When I tried to run by:

> react-native run-ios

Any idea? Thanks.

**Comment by SoHotSoup** [comment]
https://github.com/shoutem/ui/issues/50

**Comment by SoHotSoup** [comment]
`.babelrc` should be removed from ui and Restorants app folders.

**Comment by sesteva** [comment]
Just wanted to let you know the issue is still going on since the .babelrc exists on the root of the repo. Once you remove it, then the example app builds
