### ISSUE TITLE
Gradient Backgrounds

### ISSUE THREAD

**Issue by belohlavek** [shoutem/ui#60]
Is there a way to set up background gradients for NavigationBars and Buttons?

Thanks for the great project!

**Comment by SoHotSoup** [comment]
We had support for it in v0.8.0 but then we experience some problems within React Native 0.28.0, I am going to check does it work now.

**Comment by belohlavek** [comment]
Please do! 😄

**Comment by mosesmc52** [comment]
Hi, 

Do you now have support for the background?

Moses

**Comment by SoHotSoup** [comment]
Hey @belohlavek and @mosesmc52 at the moment there are to ways to achieve the gradient, if you need it just for `NavigationBar` just use `fade` styleName, and we also have this component https://github.com/shoutem/ui/blob/develop/components/LinearGradient.js, but somehow isn't exported, so if you want to address that, please add it to our index.js.
Also, we will introduce `backgroundGradient` property in style, so if you define that in any our view, it would render LinearGradient as its first child. But that is going to be available with next release.

**Comment by mosesmc52** [comment]
So the backgroundGradient property is not in the current version, but will be included in the next update of the shoutem ui kit? Is that true? If so, when?

**Comment by SoHotSoup** [comment]
I'm waiting for few PRs to be merged, which I expect could be done tomorrow.

**Comment by mosesmc52** [comment]
I assume the that in order to apply the background gradient to a RN view I just use  styleName="backgroundGradient" and all of the children of that tree element will have a background gradient. Is there anyway I could apply different colors to achieve different background gradients?

**Comment by SoHotSoup** [comment]
So, with v0.12.0 if you add `backgroundGradient` on our `View` it will render LinearGradient as its root child https://github.com/shoutem/ui/blob/9d45770d1024787f0c2c20a8ad4705a7657d3044/components/View.js#L14
