### ISSUE TITLE
Error saving ui-module

### ISSUE THREAD

**Issue by jackbillstrom** [shoutem/ui#62]
Hi, with the /cli module failing I was trying to accomplish some testing with the UI-module atleast, I've setup all the dependencies and when I'm running `npm i -S @shoutem/ui` I get this error....

```
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.

> @shoutem/ui@0.9.1 postinstall C:\Users\jb\Documents\Appar\Bira\node_modules\@shoutem\ui
> react-native link

Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-S" "@shoutem/ui"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! @shoutem/ui@0.9.1 postinstall: `react-native link`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @shoutem/ui@0.9.1 postinstall script 'react-native link'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @shoutem/ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-native link
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @shoutem/ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @shoutem/ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jb\Documents\Appar\Bira\npm-debug.log
```

Npm version:  3.10.3
Node version: v6.7.0
OS: Windows

**Comment by SoHotSoup** [comment]
You have to instal react-native-cli

`npm install -g react-native-cli`

**Comment by jackbillstrom** [comment]
Already did, followed "To fix the issue, run:"

**Comment by SoHotSoup** [comment]
Ok, have you tried to install @shoutem/ui again? Does it pass now?
It seems to me that it would be enough to run `react-native link` from your projects' root folder

Could you try build your app and confirm that everything works now?

**Comment by jackbillstrom** [comment]
Same error even though I have the `react-native-cli` and uninstalled the `react-native`. FYI am I unable to install your @shoutem/cli (Does not exist on npm?)

**Comment by SoHotSoup** [comment]
@shoutem/cli is not public yet, it would be when we release Extensions, public beta is coming soon, we'll let you know when is available.

@jackbillstrom In order to fix the error, have you tried just to run `react-native link` within your project? Also, could I ask you, to write your react native version here?

**Comment by jackbillstrom** [comment]
Yeah, I did run `react-native link `within my RN project but no success or output.

This is my versions:

```
react-native-cli: 1.0.0
react-native: 0.34.1
```

**Comment by SoHotSoup** [comment]
Ok, I'll test it later and report you. It seems to me that this is something introduced in new RN version because it normally passes with RN0.33.0

Thank you!

**Comment by jackbillstrom** [comment]
I see, well I'm looking forward to your answer. In the "worst" case I just try to downgrade RN down to 33.0.  Cheers!

**Comment by jackbillstrom** [comment]
@SoHotSoup Actually tried with an project using RN 0.33.0, still no luck so you know!

**Comment by putuyoga** [comment]
i have same issue with this one.

**Comment by ufon** [comment]
+1 @putuyoga

**Comment by ufon** [comment]
solution: 
`npm install --save @shoutem/ui --ignore-scripts`
after that:
`react-native link`
but i'm not sure maybe this script are important
`"test": "mocha -R spec --require test-utils/setup.js --require react-native-mock/mock.js --compilers js:babel-core/register $(find . -name '*.spec.js' ! -ipath '*node_modules*')",`

**Comment by jackbillstrom** [comment]
Why didn't I thought of it....cheers mate!

**Comment by anhnt** [comment]
you saved my hour @ufon 👍

**Comment by SoHotSoup** [comment]
#86

**Comment by rockus123** [comment]
Why so hard even during installation? Programmers should make things like these simple.
