### ISSUE TITLE
Not support latest version of React

### ISSUE THREAD

**Issue by jsonpreet** [shoutem/ui#627]
**npm install --save @shoutem/ui
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ghbase@0.0.1
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9.0" from @shoutem/ui@4.5.1
npm ERR! node_modules/@shoutem/ui
npm ERR!   @shoutem/ui@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Harpreet\AppData\Local\npm-cache\eresolve-report.txt for a full report.  

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Harpreet\AppData\Local\npm-cache\_logs\2021-08-09T05_59_35_994Z-debug.log**

**Comment by cayleyh** [comment]
This is resolved in newer versions. The specific version referenced in this issue is 2 major updates behind (4.x).
