### ISSUE TITLE
Text Component - Failed prop type: Invalid prop `style` of type `number`

### ISSUE THREAD

**Issue by tomardern** [shoutem/ui#65]
Hi,

When I'm trying to style a Shoutem <Text> component, I get the following error:

`ExceptionsManager.js:82 Warning: Failed prop type: Invalid prop `style` of type `number` supplied to `Styled(AnimatedComponent)`, expected `object`.`

Example code:
 
```
<Text style={styles.upNext}> Hello world!</Text>
const styles = StyleSheet.create({
    upNext:{
        textAlign:"center",
        fontSize:20
    }
});
```

**Comment by SoHotSoup** [comment]
https://github.com/shoutem/ui/issues/51

**Comment by tenodi** [comment]
Our components do not function with styles created with `StyleSheet.create`.
