### ISSUE TITLE
Receiving "Including unexisting style: richMediaTextStyle" when using components

### ISSUE THREAD

**Issue by notjosh** [shoutem/ui#67]
It seems [these](https://github.com/shoutem/ui/blob/e4cbe6b79fae8812dfa662ad973b6e69447821a8/theme.js#L874-L879) refer to an undefined style, and throws out a warning (which RN covers part of the screen to show).

I've worked around it locally by defining:

```
const theme = {
  ...getTheme(),
  richMediaTextStyle: {},
};
```

But do you need to remove it, or define something in your default theme? Either way is fine with me.

**Comment by theobouwman** [comment]
Having the same problem, how to fix?

**Comment by notjosh** [comment]
@theobouwman either use the patch in #74, or define the style in your theme as `richMediaTextStyle: {}`

**Comment by ENDiGo** [comment]
@notjosh I defined the style in my custom theme but warning still shows.
``
const theme = {
  ...getTheme(),
  richMediaTextStyle: {},
  defaultFont: {
    fontFamily: fontFamily,
  },
};
``
In component
``
<StyleProvider style={theme}>
  <Root/>
</StyleProvider>
``

**Comment by notjosh** [comment]
@ENDiGo I'm not sure then. That is working for us, but you might have a different setup. Sorry, you'll have to wait for one of project owners, I guess!

**Comment by zackify** [comment]
This is happening for me since updating to React Native 0.37.
