### ISSUE TITLE
Cannot install from npm

### ISSUE THREAD

**Issue by mnbao1975** [shoutem/ui#69]
Hi,

Here is the error I got when I tried to install with command "npm i -S @shoutem/ui".

Invalid name: "@shoutem/ui"

I'm using node 4.6.0.

Thanks,
Bao

**Comment by tenodi** [comment]
Do: 
```
npm -v
```

What does it say? `npm` version needs to be greater than 2.7.0. In case it's not, run:
```
npm install -g npm
```

Sometimes, you'll need to put `sudo` in front of that command as well.

**Comment by mnbao1975** [comment]
Thank you for quick feedback. My npm version is 2.15.9. Anyhow, I used yarn client to install the module and it works.

Bao
