### ISSUE TITLE
Searchbar at the top of ListView

### ISSUE THREAD

**Issue by infacq** [shoutem/ui#75]
How do I make a search bar when the page scroll to the top only. Thank you

**Comment by infacq** [comment]
actually I saw this behaviour on whatsapp app for ios. When user scroll down at the top of the page then the searchbar appear. How do I prepare such component

**Comment by MrBr** [comment]
`ListView` is always showing `data` you provide, so to show filtered results you have to provide **filtered** `data`.

In your case, when you enter search term you need to filter `dataSource`. You can filter data before grouping if you have search term (in `_renderProducts`). 

```
  _renderProducts(List) {
    // You have to implement filterBySearchTerm
    const preparedList = this.state.search ? List.filter(filterBySearchTerm) : List;
    const groupedList = GridRow.groupByRows(preparedList, 2);
    return (
      <ListView data={ groupedList } stickyHeaderIndices={[0]} loading={true} renderRow={ this._renderRow } renderHeader={() => <ListViewSearchHeader onSearchChange={this.onSearchChange} search={this.state.search} />} />
    )
  }
```

Notes:

- Think about debouncing `onChangeText`, you do not want to refresh state while still typing
- Whenever you change `ListView` data reference ListView is going to rerender

**Comment by infacq** [comment]
thanks for the enlightment. but right now what I need is to hide the searchbar on initial appearance then only appear if user drag down the list

**Comment by ishsingh** [comment]
@infacq Use autoHideHeader along with renderHeader method. This is how I am doing it:

`        <ListView
            autoHideHeader={true}
            data={this.state.data}
            loading={this.state.isLoading}
            onLoadMore={this.onEndReached}
            onRefresh={this.onSearchChanged}
            renderRow={this.renderRow}
            renderHeader={this.renderHeader}
            style={{backgroundColor: colors.black}}
        />
`
Then the renderHeader method looks like this.

`  renderHeader: function() {
    return (
      <View>
      <SearchBar
        containerStyle={{backgroundColor : colors.black }}
        round
        onChangeText={(text) => this.setState({ search: text})}
        onSubmitEditing={this.onSearchChanged}
        placeholder='Type Here...'>
      </SearchBar>
      </View>
    )
  }`

**Comment by larafale** [comment]
hello guys, i can't figure out how to clear the spinner when it's triggered by an `onPress` function (aka pull to refresh), any idea ?

**Comment by ishsingh** [comment]
Use the this.setState({ isLoading : false }) after fetching the data is complete.

isLoading is the state variable that you specify in the ListView's settings.

On Jan 6, 2017, at 1:58 PM, louis <notifications@github.com<mailto:notifications@github.com>> wrote:


hello guys, i can't figure out how to clear the spinner when it's triggered by an onPress function (aka pull to refresh), any idea ?
