### ISSUE TITLE
TextInput error when using secureTextEntry={true}

### ISSUE THREAD

**Issue by aessig** [shoutem/ui#77]
When I add secureTextEntry={true} to a shoutem/ui TextInput, I have the following error: 
`Unrecognized font family 'Rubik'`
I have been able to track the error up to this line in **components/TextInput.js**

```
const AnimatedTextInput = connectAnimation(TextInput);
const StyledTextInput = connectStyle('shoutem.ui.TextInput')(AnimatedTextInput);
```

I fixed the bug by doing that

```
//const AnimatedTextInput = connectAnimation(TextInput);
const StyledTextInput = connectStyle('shoutem.ui.TextInput')(TextInput);
```

because I tried to find the bug in connectAnimation, but I couldn't find anything strange and I have no clue what it could be

**Comment by ENDiGo** [comment]
Maybe you didn't run 
```
react-native link
```
