### ISSUE TITLE
DropDownMenu onOptionSelected issue

### ISSUE THREAD

**Issue by pvpshoot** [shoutem/ui#91]
DropDownMenu fires a function after render, not on tapping an option from menu

```javascript
<DropDownMenu
  titleProperty={'name'}
  valueProperty={'id'}
  options={TMPARRAY}
  onOptionSelected={console.log}
/>
```

**Comment by SoHotSoup** [comment]
Hey! Thank you for this one, we are already working on it.

**Comment by pvpshoot** [comment]
I just use `_` for fix it.
smth like this:
```javascript
onOptionSelected={partial(cb, _, myOsmValue)}


if (option.name !== myOsmValue) return null;
```

**Comment by SoHotSoup** [comment]
Hey @pvpshoot we have changed `DropDownMenu` interface with latest release ~0.10.0 so this should not happen anymore. Thank you for pointing it out!

**Comment by ekmutai** [comment]
onOptionSelected doesn't seem to be working even on <Examples /> i can't switch from the typography option, only close button works.
am using "@shoutem/ui": "^0.21.2" , and i set up the project using create-react-app
![simulator screen shot 15 aug 2017 17 32 20](https://user-images.githubusercontent.com/2639438/29321570-82b9f584-81e3-11e7-8468-2907de72d557.png)
