### ISSUE TITLE
Unrecognized font family 'Rubik-Regular'

### ISSUE THREAD

**Issue by r-bansal** [shoutem/ui#95]
Error using app `Unrecognized font family 'Rubik-Regular'`. App works fine after dismissing. Just posting this since I could not resolve it through other issues I found online.

Also, unable to load `RestaurantsApp` until I upgraded RN 0.38. 

Will post a PR if I am able to resolve.

**Comment by SoHotSoup** [comment]
Hey @r-bansal! Thank you for submitting this issue.
This looks like something gone wrong with `react-native link`. Could you try to link it again and post here the answer? If that was the issue, we will release the fix this week.

**Comment by jackbillstrom** [comment]
Same error appears for me, version below.
```
jays-Air:washery jack$ react-native -v
react-native-cli: 1.3.0
react-native: 0.36.1
```
```
jays-Air:washery jack$ react-native link
(node:36815) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
(node:36815) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
rnpm-install info Linking assets to ios project 
rnpm-install info Linking assets to android project 
rnpm-install info Assets have been successfully linked to your project 
jays-Air:washery jack$ 
```

**Comment by Satya5614** [comment]
I had the same issue even after trying to link it again, but restarting the app using `react-native run-ios` resolved the issue for me

**Comment by benjaminb10** [comment]
Hi, Same issue here. And neither `react-native link` or `react-native run-ios` solve the issue.

**Comment by tedjames** [comment]
@benjaminb10 Why do you think it's because you're using RN 0.40?

**Comment by benjaminb10** [comment]
'Cause when I've tested with a new RN 0.39 app it was working.

**Comment by jasdeepsingh** [comment]
I have the same issue, this is what I'm using:

```
react-native-cli: 2.0.1
react-native: 0.40.0
```

It seems it's broken for `0.40.0`

**Comment by housseindjirdeh** [comment]
Experiencing the same issue.

**Comment by suhabaobaid** [comment]
Same issue, none of linking or rerunning the app worked. Any updates on this issue?

**Comment by paduvi** [comment]
Same here, hope for quick update

**Comment by ojardila** [comment]
the same issue

**Comment by suhabaobaid** [comment]
@ojardila @paduvi I found a fix. You have to add the fonts file in Xcode and re run it. Follow this example https://github.com/oblador/react-native-vector-icons#installation . see the option manually and whichever font u include in ur app also include it in Xcode. 
Happy coding :)

**Comment by andersonsousa** [comment]
Same problem here. Files are in the project and referenced in info.plist, but I keep getting this message.

**Comment by mhaagens** [comment]
Same issue.

**Comment by acomito** [comment]
I am getting this too. It brings development to a stand still. Help!

**Comment by hari-sree** [comment]
Faced the issue today :(

**Comment by oliwerhelsen** [comment]
Yeah same for me:-(

**Comment by pedroborges** [comment]
I'm just trying out Shoutem UI and got the same error…

**Comment by joinjoohny** [comment]
Same issues...
`
react-native-cli: 2.0.1
react-native: 0.40.0
`

**Comment by evelan** [comment]
Why it is closed? Same issue `react-native 0.40.0`

**Comment by comiclee** [comment]
A resolution is that drag the folder 'node_modules/@shoutem/ui/fonts' to your project in Xcode. And then edit Info.plist, add a property called Fonts provided by application and add the fonts to the list. Like this:
![image](https://cloud.githubusercontent.com/assets/5093098/22681125/987bfcb4-ed46-11e6-880c-d6a5f0388242.png)

**Comment by andersonsousa** [comment]
My project already has this fonts listed. But the error remains. :/

**Comment by 3DEsprit** [comment]
I had this same issue with a brand new project, after installing @shoutem/ui. At first I had to deal with Issue #134 (update and re-link imports), then the build succeeded. Unfortunately, as soon as I added a NavigationBar, I was presented with this missing font error as well. The Fonts do in fact exist in the Xcode project, as well as in the node_modules.

RN: 0.40
XCode: 8.2.1
ShoutEm/UI: 0.10.9
react-native-vector-icons: 2.0.3

Even though I had relinked the icon package when working with the first issue, re-linking **react-native-vector-icons** explicitly, allowed me to resolve this issue. 

`$ react-native link react-native-vector-icons`

I know it is quite simple, and may not work for everyone, but in my case it is what worked.

**Comment by dazziola** [comment]
Broken in 0.41.2 as well. @SoHotSoup can we get this reopened please? It seems like the vast majority are experiencing this bug.

**Comment by SoHotSoup** [comment]
@dazziola I can really promise you we will release a new version next week, and really sorry for this issue.

**Comment by SoHotSoup** [comment]
And thank you guys for being that patient!

**Comment by mypark** [comment]
Hey I tried `react-native link react-native-vector-icons` but now I get these errors fro RNVectorIcons `Redefinition of RCTLogLevel...` and a bunch of other errors.  Anyone know how to fix or undo?  Unlinking didn't work.

**Comment by willluck** [comment]
I use "npm i -S react-native-vector-icons" and "npm i -S react-native-linear-gradient" to solve problem ,but I use "NavigationBar",always can't use  " styleName="clear"",if I use ,the "NavigationBar" will disappear,@SoHotSoup , How can I fix it?

**Comment by SoHotSoup** [comment]
Hey @willluck, I don't really understand what is the problem, could you attach some screenshot or write exact code snippet here?

**Comment by csbun** [comment]
Thanks @willluck , this fixed!

```
yarn add react-native-vector-icons
yarn add react-native-linear-gradient
```

Or using `npm i -S`;

**Comment by willluck** [comment]
Thanks ,but use "NavigationBar" and set " styleName="clear" ,the effect will be displayed correctly?@csbun

**Comment by csbun** [comment]
It comes out something like this:
![image](https://cloud.githubusercontent.com/assets/1468366/23399468/42cfa2ac-fddb-11e6-8ae2-2895e4662f79.png)

Here are my code:

```
<Screen>
  <NavigationBar
      styleName="clear inline"
      leftComponent={<Icon name="sidebar" />}
      centerComponent={<Title>TITLE</Title>}
  />
</Screen>
```

**Comment by willluck** [comment]
Yes,if use `styleName="clear` ,the `centerComponent={<Title>TITLE</Title>}` will disappear@csbun,@SoHotSoup

**Comment by anselmdk** [comment]
This solution also worked for me:

```
yarn add react-native-vector-icons
yarn add react-native-linear-gradient
```

**Comment by SoHotSoup** [comment]
This is fixed with latest release v0.12.0. Thank you guys for being this patient!

**Comment by uc-asa** [comment]
@comiclee Thanks, I have using same tricks and it works for me.

**Comment by annedroiid** [comment]
This just happened to me in v0.12.1

**Comment by maulberto3** [comment]
Hi @annedroiid  I am having the same issue, tried with [this](https://github.com/shoutem/ui/blob/develop/examples/create-react-native-app/App.js) but still can´t get to load that font. Any suggestions?
