### ISSUE TITLE
`MapView` has no propType for native prop `AIRMap.showsMyLocationButton` of native type `boolean`

### ISSUE THREAD

**Issue by leocavalcante** [shoutem/ui#96]
Ps.: I'm not using `MapView`, just imported `View`, `NavigationBar` and `Title` from `@shoutem/ui`

![image](https://cloud.githubusercontent.com/assets/183722/20678151/d33de184-b57c-11e6-8aa7-3495298eac9f.png)

Exponent logs:
```
15:02:11
Warning: Native component for "RCTVideo" does not exist
15:02:11
Warning: ReactClass: You're attempting to include a mixin that is either null or not an object. Check the mixins included by the component, as well as any mixins they include themselves. Expected object but got undefined.
```

**Comment by Vunovati** [comment]
Which shoutem/ui version are you using? Did you run `react-native link`? I can see you are using exponent. Try installing the app without using `react-native link` ... make sure you follow the special instruction for exponent users below: https://github.com/shoutem/ui#examples-component

**Comment by leocavalcante** [comment]
Installed version 0.9.1. Using `--ignore-scripts` to avoid `react-native link` on postinstall.
I guess this is tight related to #58 , deleting `/node_modules/@shoutem/ui/node_modules/react-native-maps` works.
